#!/usr/bin/env python3
"""Suites (tc-copilot-spec §9): selection, never generation.

`wiki suite compile <name>` filters ACTIVE TCs from the wiki per
suites/<name>.yaml and writes build/inventory/<name>.md + .xlsx.
Zero LLM calls, zero writes outside build/ (spec P7, acceptance test 3).
Retired TCs render in a separate section; stale TCs are listed but flagged.
"""
import math
import re
import sys
from datetime import date, datetime
from pathlib import Path

import yaml

from wiki import ROOT, body_section, load_all, load_config, load_manifest, resolve_ref

HEADER = "<!-- generated by wiki suite compile — reproducible from manifest + wiki; do not edit -->\n"


def tc_sort_key(fm):
    # A TC covering a flow journey fragment (#J\d+) sorts by journey position
    # ahead of everything, so UAT sheets read in walk order (module key "" wins).
    for ref in fm.get("covers") or []:
        rel, frag = resolve_ref(ref)
        if rel.startswith("flows/") and frag and re.match(r"^J\d+$", frag):
            return ("", (), 0, int(frag[1:]), fm["id"])
    m = re.match(r"^(?:UAT-)?(\d[\d.]*)-AC(\d+)-(\d+)$", fm["id"])
    if not m:
        return (fm.get("module") or "", (), 999, 999, fm["id"])
    prefix = tuple(int(p) for p in m.group(1).split("."))
    return (fm.get("module") or "", prefix, int(m.group(2)), int(m.group(3)),
            fm["id"])


def select(suite, concepts):
    """Returns (selected, retired, stale_included) lists of (rel, fm, body)."""
    kind = suite.get("kind", "sit")
    inc_mod = suite.get("include_modules") or []
    exc_mod = suite.get("exclude_modules") or []
    inc_flow = suite.get("include_flows") or []
    exc_flow = suite.get("exclude_flows") or []
    prios = suite.get("priorities") or []
    extra_inc = set(suite.get("extra_include") or [])
    extra_exc = set(suite.get("extra_exclude") or [])

    selected, retired, stale = [], [], []
    for rel, (fm, body, _p) in sorted(concepts.items()):
        if not fm or fm.get("type") != "Test Case":
            continue
        if kind != "mixed" and fm.get("kind") != kind:
            continue
        mod = Path(resolve_ref(fm["module"])[0]).name if fm.get("module") else None
        flow = Path(resolve_ref(fm["flow"])[0]).name if fm.get("flow") else None
        in_scope = True
        if inc_mod and (mod not in inc_mod):
            in_scope = False
        if mod in exc_mod:
            in_scope = False
        if inc_flow and (flow not in inc_flow):
            in_scope = False
        if flow in exc_flow:
            in_scope = False
        if prios and fm.get("priority") not in prios:
            in_scope = False
        if fm["id"] in extra_inc:
            in_scope = True
        if fm["id"] in extra_exc:          # subtractive wins (spec §9)
            in_scope = False
        if not in_scope:
            continue
        st = fm.get("status")
        if st == "active":
            selected.append((rel, fm, body))
        elif st == "retired":
            retired.append((rel, fm, body))
        elif st == "stale":
            stale.append((rel, fm, body))
    keyf = lambda t: tc_sort_key(t[1])
    return sorted(selected, key=keyf), sorted(retired, key=keyf), sorted(stale, key=keyf)


# ------------------------------------------------------------------ xlsx
# SIT workbook format (template: tools/reference-format-sit.xlsx = the
# reference SIT workbook layout, a synthetic example generated by
# tools/make_reference_workbooks.py). Five sheets:
#   A - Table of Contents · B - Proj Doc References · one C-TC-<sec> sheet
#   per module · Test Statistics · Change Log
# TC sheet columns A-L; F-L are execution columns left blank for testers.

TC_COLS = ("Test Case ID", "Scenario", "Test Steps", "Field / Values",
           "Expected Results", "Actual Results", "Status", "Tested by",
           "Date Tested", "Retested by", "Retested Date", "Remarks")
COL_W = dict(zip("ABCDEFGHIJKL", (26, 66, 51, 31, 66, 26, 16, 12, 12, 12, 13, 20)))
STATUSES = ("Pass", "Fail", "Block", "Void", "Not Yet Tested", "Pending Retest")
TC_HEADER_ROW = 8      # header row on every C-TC sheet; Status is column G
STATS_FIRST_ID_ROW = 22


def _styles():
    from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
    thin = Side(style="thin")
    return dict(
        border=Border(left=thin, right=thin, top=thin, bottom=thin),
        hdr_fill=PatternFill("solid", fgColor="D9D9D9"),
        exec_fill=PatternFill("solid", fgColor="92D050"),
        sect_fill=PatternFill("solid", fgColor="BFBFBF"),
        top=Alignment(wrap_text=True, vertical="top"),
        center=Alignment(wrap_text=True, vertical="center", horizontal="center"),
        font=lambda **kw: Font(name="Arial", **{"size": 10, **kw}),
        blue=Font(name="Arial", size=10, bold=True, color="0070C0"),
    )


def _fm_of(concepts, rel):
    c = concepts.get(rel)
    return c[0] if c else None


# tc-style contract (skill .claude/skills/tc-style): workbook text uses
# hyphens (never em/en dashes) and renders `**...**` markers as real bold.
_DASHES = {0x2014: "-", 0x2013: "-"}
_BOLD_RE = re.compile(r"\*\*(.+?)\*\*", re.DOTALL)


def _plain(text):
    """Marker-free, dash-normalized text (for height estimation / md output)."""
    return _BOLD_RE.sub(r"\1", str(text).translate(_DASHES))


def _richify(text):
    """Cell value per tc-style: em/en dashes -> hyphens; '**...**' markers ->
    rich-text bold runs. Returns a plain str when nothing is bold."""
    s = str(text).translate(_DASHES)
    if "**" not in s:
        return s
    from openpyxl.cell.rich_text import CellRichText, TextBlock
    from openpyxl.cell.text import InlineFont
    bold = InlineFont(rFont="Arial", sz=10, b=True)
    rich = CellRichText()
    for i, part in enumerate(_BOLD_RE.split(s)):
        if part:
            rich.append(TextBlock(bold, part) if i % 2 else part)
    return rich


def _display_id(fm):
    # Org sheets prefix ids with "TC-" (e.g. TC-1.1.3.1.1-AC1-01); the sheet's
    # Total-TC COUNTIF and the Test Statistics VLOOKUPs key off this form.
    # UAT ids carry a "UAT-" prefix in the wiki; strip it to the org "TC-" form.
    tid = fm["id"]
    if tid.startswith("UAT-"):
        return "TC-" + tid[4:]
    return tid if tid.startswith(("TC-", "BR-")) else f"TC-{tid}"


def _ac_text(fm, concepts):
    for ref in fm.get("covers") or []:
        rel, frag = resolve_ref(ref)
        sfm = _fm_of(concepts, rel)
        if not (sfm and frag):
            continue
        for key in ("acceptance_criteria", "branches"):
            for ac in sfm.get(key) or []:
                if ac.get("id") == frag:
                    return ac.get("text") or ""
    return ""


def _scenario_cell(fm, body, concepts):
    """Template Scenario column: 'Scenario/Given/When/Then' parsed from the
    covered AC's Gherkin-in-prose text; falls back to the TC objective."""
    text = " ".join(_ac_text(fm, concepts).split())
    m = re.match(r"^(?P<t>.+?\.)\s+Given (?P<g>.+?), when (?P<w>.+?), then (?P<n>.+)$",
                 text, re.IGNORECASE)
    if m:
        g, w, n = (m.group(k).rstrip(".") for k in "gwn")
        return (f"**Scenario:** {m.group('t')}\n\n**Given:** {g[:1].upper()}{g[1:]}.\n\n"
                f"**When:** {w[:1].upper()}{w[1:]}.\n\n**Then:** {n[:1].upper()}{n[1:]}.")
    obj = body_section(body, "Objective") or fm.get("description") or ""
    return f"**Scenario:** {fm['title']}.\n\n{obj}".strip()


def _precond_lines(body):
    sec = body_section(body, "Preconditions") or ""
    return [re.sub(r"^\d+\.\s*", "", ln.strip())
            for ln in sec.splitlines() if ln.strip()]


def _subgroup_of(fm, concepts):
    """(rel, fm) of the first covering story; falls back to the flow.

    Story-from-covers is tried FIRST so UAT sheets (whose TCs carry a `flow`
    but cover a story AC) group by screen (the member story) rather than
    collapsing every UAT TC under the single flow."""
    for ref in fm.get("covers") or []:
        rel, _frag = resolve_ref(ref)
        sfm = _fm_of(concepts, rel)
        if sfm and sfm.get("type") == "User Story":
            return rel, sfm
    if fm.get("flow"):
        rel = resolve_ref(fm["flow"])[0]
        return rel, _fm_of(concepts, rel)
    return None, None


def _group(tcs, concepts):
    """[(mod_rel, mod_fm, [(sub_rel, sub_fm, [tc, ...]), ...]), ...]
    Modules and subgroups keep first-TC order (tcs arrive sorted)."""
    mods, order = {}, []
    for rel, fm, body in tcs:
        mrel = resolve_ref(fm.get("module") or fm.get("flow") or "unassigned")[0]
        if mrel not in mods:
            mods[mrel] = {}
            order.append(mrel)
        srel, sfm = _subgroup_of(fm, concepts)
        mods[mrel].setdefault(srel, (sfm, []))[1].append((rel, fm, body))
    return [(mrel, _fm_of(concepts, mrel),
             [(srel, sfm, tcl) for srel, (sfm, tcl) in mods[mrel].items()])
            for mrel in order]


def _sheet_name(mod_fm, idx):
    desc = (mod_fm or {}).get("description") or ""
    m = re.search(r"§(\d+(?:\.\d+)*)", desc)
    sec = m.group(1) if m else str(idx + 1)
    title = _plain((mod_fm or {}).get("title") or "Test Cases")
    name = f"C-TC-{sec} ({title})"
    while len(name) > 31:                    # Excel sheet-name hard limit
        words = title.split()
        i = max(range(len(words)), key=lambda j: len(words[j]))
        if len(words[i]) <= 4:
            title = title[:len(title) - (len(name) - 31)].rstrip()
            name = f"C-TC-{sec} ({title})"
            break
        words[i] = words[i][:4]
        title = " ".join(words)
        name = f"C-TC-{sec} ({title})"
    return re.sub(r"[\[\]:*?/\\']", "-", name)


def _est_height(vals):
    lines = 1
    for col, val in zip("ABCDE", vals):
        if not val:
            continue
        w = max(COL_W[col] - 2, 10)
        n = sum(max(1, math.ceil(len(ln) / w)) for ln in _plain(val).split("\n"))
        lines = max(lines, n)
    return min(max(14 * lines, 20), 400)


def _fill_toc(ws, exp, meta, st):
    ws["B1"] = meta.get("title_prefix", "") + "AGILE TEST SPECIFICATIONS - Table of Contents"
    ws["B1"].font = st["font"](bold=True, size=14)
    rows = [(3, "Project Code", exp.get("project_code", "")),
            (4, "Project Name", exp.get("project_name", "")),
            (5, "System/Subsystem Name (if applicable)", exp.get("system_name", "")),
            (6, "Module Name (if applicable)", meta["module_name"]),
            (7, "Test Type", meta["test_type"]),
            (8, "Version No.", meta["version"]),
            (9, "Prepared by / Date",
             f"{exp.get('prepared_by', 'tc-copilot')} / {meta['prepared_date']}"),
            (10, "Reviewed by / Date", ""),
            (12, "Test Execution Cycle", meta["test_type"]),
            (13, "Test Execution Period",
             "From <dd/mm/yyyy> to <dd/mm/yyyy> - to be filled during test execution"),
            (14, "Test Result As At", "<dd/mm/yyyy> - to be filled during test execution")]
    for r, label, val in rows:
        ws.cell(row=r, column=1, value=label).font = st["font"](bold=True)
        ws.cell(row=r, column=3, value=val).font = st["font"]()
    ws.cell(row=16, column=1, value="Revision History").font = st["font"](bold=True, size=12)
    for col, h in enumerate(("Version", "Effective Date", "Summary of Changes", "Author"), 1):
        c = ws.cell(row=17, column=col, value=h)
        c.font, c.fill, c.border = st["font"](bold=True), st["hdr_fill"], st["border"]
    for col, v in enumerate((meta["version"], meta["date"],
                             meta.get("revision_summary", "Generated by tc-copilot (wiki export)"),
                             exp.get("prepared_by", "tc-copilot")), 1):
        c = ws.cell(row=18, column=col, value=v)
        c.font, c.border = st["font"](), st["border"]
    ws.cell(row=21, column=1, value="Table of Contents").font = st["font"](bold=True, size=12)
    for col, h in enumerate(("Tab", "Title"), 1):
        c = ws.cell(row=22, column=col, value=h)
        c.font, c.fill, c.border = st["font"](bold=True), st["hdr_fill"], st["border"]
    for i, (tab, tab_title) in enumerate(meta["tabs"]):
        for col, v in enumerate((tab, tab_title), 1):
            c = ws.cell(row=23 + i, column=col, value=v)
            c.font, c.border = st["font"](), st["border"]
    ws.column_dimensions["A"].width = 38
    ws.column_dimensions["B"].width = 22
    ws.column_dimensions["C"].width = 60
    ws.column_dimensions["D"].width = 22


def _fill_refs(ws, meta, st):
    ws["B1"] = "AGILE TEST SPECIFICATIONS\n- Project Document References"
    ws["B1"].font = st["font"](bold=True, size=14)
    ws["B1"].alignment = st["top"]
    labels = (("A3", "Project Code / Name",
               "=CONCATENATE('A - Table of Contents'!$C$3,\"/ \",'A - Table of Contents'!$C$4)"),
              ("A4", "System/Subsystem/Module",
               "=CONCATENATE('A - Table of Contents'!$C$5,\"/ \",'A - Table of Contents'!$C$6)"),
              ("A5", "Test Type / Version No.",
               "=CONCATENATE('A - Table of Contents'!$C$7,\"/ \",'A - Table of Contents'!$C$8)"))
    for coord, label, formula in labels:
        ws[coord] = label
        ws[coord].font = st["font"](bold=True)
        c = ws.cell(row=ws[coord].row, column=3, value=formula)
        c.font = st["font"]()
    for col, h in enumerate(("Document Type", "Document Name and version"), 1):
        c = ws.cell(row=7, column=1 if col == 1 else 3, value=h)
        c.font, c.fill, c.border = st["font"](bold=True), st["hdr_fill"], st["border"]
    for i, (dtype, dname) in enumerate(meta["docs"]):
        a = ws.cell(row=8 + i, column=1, value=dtype)
        b = ws.cell(row=8 + i, column=3, value=dname)
        a.font = b.font = st["font"]()
        a.border = b.border = st["border"]
    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["C"].width = 70


def _fill_tc_sheet(ws, mod_fm, subs, concepts, exp, st):
    ws["B2"] = "AGILE TEST SPECIFICATIONS - Test Cases"
    ws["B2"].font = st["font"](bold=True, size=12)
    ws["C3"] = '=CONCATENATE("Total TC = ",COUNTIF(A:A,"TC-*")+COUNTIF(A:A,"BR-*"))'
    ws["C3"].font = st["font"](bold=True)
    for r, label in ((4, "Project Code / Name"), (5, "System/Subsystem/Module"),
                     (6, "Test Type / Version No.")):
        ws.cell(row=r, column=1, value=label).font = st["font"](bold=True)
    ws["B4"] = "=CONCATENATE('A - Table of Contents'!$C$3,\"/ \",'A - Table of Contents'!$C$4)"
    ws["B5"] = "=CONCATENATE('A - Table of Contents'!$C$5,\"/ \",'A - Table of Contents'!$C$6)"
    ws["B6"] = "=CONCATENATE('A - Table of Contents'!$C$7,\"/ \",'A - Table of Contents'!$C$8)"
    for coord in ("B4", "B5", "B6"):
        ws[coord].font = st["font"]()
    if exp.get("roles"):
        c = ws.cell(row=7, column=4, value=exp["roles"])
        c.font, c.fill, c.alignment = st["font"](bold=True), st["hdr_fill"], st["center"]
    c = ws.cell(row=7, column=6, value="Update during Test Execution")
    c.font, c.fill, c.alignment = st["font"](bold=True), st["exec_fill"], st["center"]
    for col, h in enumerate(TC_COLS, 1):
        c = ws.cell(row=TC_HEADER_ROW, column=col, value=h)
        c.font, c.alignment, c.border = st["font"](bold=True), st["center"], st["border"]
        c.fill = st["hdr_fill"] if col <= 5 else st["exec_fill"]
    ws.row_dimensions[TC_HEADER_ROW].height = 38
    for col, w in COL_W.items():
        ws.column_dimensions[col].width = w
    ws.freeze_panes = f"A{TC_HEADER_ROW + 1}"

    all_tcs = [tc for _srel, _sfm, tcl in subs for tc in tcl]
    prd_secs, nums = [], []
    for _srel, sfm, tcl in subs:
        for sec in re.findall(r"§(\d[\d.]*)", (sfm or {}).get("description") or ""):
            if sec not in prd_secs:
                prd_secs.append(sec)
        for _rel, fm, _b in tcl:
            m = re.match(r"^(\d[\d.]*)-AC", fm["id"])
            if m and m.group(1) not in nums:
                nums.append(m.group(1))
    section = _plain((mod_fm or {}).get("title") or "Test Cases")
    if prd_secs:
        section += " - " + ", ".join(prd_secs)
    if nums:
        section += f" ({', '.join(nums)})"

    r = TC_HEADER_ROW + 1
    ws.cell(row=r, column=1, value=section).font = st["blue"]
    r += 1
    pre_lists = [_precond_lines(b) for _r, _f, b in all_tcs]
    common = [ln for ln in (pre_lists[0] if pre_lists else [])
              if all(ln in pl for pl in pre_lists[1:])]
    if common:
        ws.cell(row=r, column=1, value="<Pre-condition>").font = st["blue"]
        r += 1
        for i, ln in enumerate(common, 1):
            # blue block is whole-cell bold already — markers stripped, dashes fixed
            ws.cell(row=r, column=1, value=f"{i}. {_plain(ln)}").font = st["blue"]
            r += 1
    for _srel, sfm, tcl in subs:
        sub_title = _plain((sfm or {}).get("title") or "") or None
        if sub_title:
            for col in range(1, 13):
                c = ws.cell(row=r, column=col)
                c.fill, c.border = st["sect_fill"], st["border"]
            ws.cell(row=r, column=1, value=sub_title).font = st["font"](bold=True)
            ws.row_dimensions[r].height = 21
            r += 1
        for _rel, fm, body in tcl:
            data = body_section(body, "Test Data") or ""
            if data.strip() in ("-", "N/A", "_None_"):
                data = ""
            extra = [ln for ln in _precond_lines(body) if ln not in common]
            if extra:
                # tc-style R5: TC-specific setup appends as bare lines — no
                # "Pre-condition:" label, no numbering (shared lines live in
                # the sheet's blue <Pre-condition> block).
                lines = "\n".join(extra)
                data = f"{data}\n\n{lines}".strip() if data else lines
            vals = (_display_id(fm), _scenario_cell(fm, body, concepts),
                    body_section(body, "Steps") or "", data,
                    body_section(body, "Expected Results") or "")
            for col, v in enumerate(vals, 1):
                c = ws.cell(row=r, column=col, value=_richify(v))
                c.font, c.alignment, c.border = st["font"](), st["top"], st["border"]
            for col in range(6, 13):        # blank execution grid for testers
                ws.cell(row=r, column=col).border = st["border"]
            ws.row_dimensions[r].height = _est_height(vals)
            r += 1


def _fill_stats(ws, dashboards, st):
    """dashboards: [(title, tc_sheet_name, [display_id, ...]), ...]"""
    from openpyxl.utils import get_column_letter
    pct = "0.0%"
    end = STATS_FIRST_ID_ROW + max([len(d[2]) for d in dashboards] or [0]) - 1
    cols = [get_column_letter(2 + 3 * i) for i in range(len(dashboards))]
    scols = [get_column_letter(3 + 3 * i) for i in range(len(dashboards))]
    ws.cell(row=2, column=1, value="OVERALL").font = st["font"](bold=True, size=12)
    overall = (("Total TCs", 12), ("Pass", 14), ("Fail", 15), ("Block", 16),
               ("Void", 17), ("Not Yet Tested", 18), ("Pending Retest", 19))
    ws.cell(row=3, column=1, value="Total TCs").font = st["font"](bold=True)
    ws.cell(row=3, column=2, value="=" + "+".join(f"{c}12" for c in cols)).font = st["font"]()
    for i, (label, src_row) in enumerate(overall[1:], 4):
        ws.cell(row=i, column=1, value=label).font = st["font"]()
        ws.cell(row=i, column=2,
                value="=" + "+".join(f"{c}{src_row}" for c in cols)).font = st["font"]()
        c = ws.cell(row=i, column=3, value=f"=IFERROR(B{i}/$B$3,0)")
        c.font, c.number_format = st["font"](), pct
    for i, (title, _sheet, _ids) in enumerate(dashboards):
        c = ws.cell(row=11, column=2 + 3 * i, value=title)
        c.font, c.fill = st["font"](bold=True), st["hdr_fill"]
    per = (("Total TCs", 12, None),
           ("Total Executed (Pass + Fail)", 13, None)) + tuple(
        (s, 14 + j, s) for j, s in enumerate(STATUSES))
    for label, row, _s in per:
        ws.cell(row=row, column=1, value=label).font = st["font"]()
    for i, (title, _sheet, ids) in enumerate(dashboards):
        cl, sl = cols[i], scols[i]
        ws[f"{cl}12"] = f"=COUNTA({cl}${STATS_FIRST_ID_ROW}:{cl}${end})"
        ws[f"{cl}13"] = f"={cl}14+{cl}15"
        for j, status in enumerate(STATUSES):
            row = 14 + j
            ws[f"{cl}{row}"] = (f'=COUNTIF({sl}${STATS_FIRST_ID_ROW}:{sl}${end},'
                                f'"{status}")')
            c = ws[f"{sl}{row}"]
            c.value, c.number_format = f"=IFERROR({cl}{row}/{cl}$12,0)", pct
        for coord, h in ((f"{cl}21", "Test Case ID"), (f"{sl}21", "Status")):
            ws[coord] = h
            ws[coord].font, ws[coord].fill = st["font"](bold=True), st["hdr_fill"]
            ws[coord].border = st["border"]
        sheet_ref = dashboards[i][1]
        for j, tid in enumerate(ids):
            row = STATS_FIRST_ID_ROW + j
            a = ws[f"{cl}{row}"]
            a.value, a.font, a.border = tid, st["font"](), st["border"]
            b = ws[f"{sl}{row}"]
            b.value = f"=VLOOKUP({cl}{row},'{sheet_ref}'!$A:$L,7,FALSE)"
            b.font, b.border = st["font"](), st["border"]
    ws.column_dimensions["A"].width = 28
    for c in cols:
        ws.column_dimensions[c].width = 26
    for c in scols:
        ws.column_dimensions[c].width = 16


def change_rows(changes, dash_of, draft=False):
    """Rows (Dashboard, Test Case ID, Description of Change) for the Change
    Log sheet. `dash_of` maps display id -> sub-story title."""
    if draft:
        return [("", "", "Draft round 0 - no changes yet.")]
    if not changes:
        return [("", "", "No current change log - run eval_rubric --diff on "
                 "this sealed set.")]
    to = changes.get("to") or {}
    rounds = {r["round"]: r["score"] for r in changes.get("rounds") or []}
    delta = changes.get("delta")
    sign = f"{delta:+}" if isinstance(delta, (int, float)) else ""
    if changes.get("regression_restored"):
        head = (f"Graded round {to.get('round')}: {to.get('score')} (round 2 "
                f"regressed to {rounds.get(2)}, {sign}; round 1 kept), "
                f"rubric {changes.get('rubric_version', '')}")
    elif to.get("round") and to["round"] - 1 in rounds:
        head = (f"Graded round {to['round']}: {to.get('score')} (round "
                f"{to['round'] - 1}: {rounds[to['round'] - 1]}, {sign}), "
                f"rubric {changes.get('rubric_version', '')}")
    else:
        head = (f"Graded round {to.get('round')}: {to.get('score')}, "
                f"rubric {changes.get('rubric_version', '')}")
    rows = [("", "", head)]
    grouped = {}          # tc -> (kind, fields, closes, extra) in first-seen order
    for c in changes.get("changes") or []:
        tid = c["tc"]
        kind = c["kind"]
        if kind not in ("added", "removed", "changed"):
            raise ValueError(f"change_rows: unknown change kind {kind!r} for {tid}")
        disp = _display_id({"id": tid})
        g = grouped.setdefault(disp, {"kind": kind, "fields": [], "closes": [],
                                      "title": c.get("title", ""), "reason": c.get("reason", "")})
        if c.get("field") and c["field"] not in g["fields"]:
            g["fields"].append(c["field"])
        for cl in (c.get("closes") or "").split(","):
            cl = cl.strip()
            if cl and cl not in g["closes"]:
                g["closes"].append(cl)
    for disp, g in grouped.items():
        closes = f" (closes {', '.join(g['closes'])})" if g["closes"] else ""
        if g["kind"] == "added":
            desc = f"Added - {g['title']}{closes}"
        elif g["kind"] == "removed":
            desc = f"Removed - {g['reason'] or 'not in the current set'}"
        elif g["kind"] == "changed":
            desc = f"Changed {', '.join(g['fields'])}{closes}"
        rows.append((dash_of.get(disp, ""), disp, desc))
    return rows


def _fill_change_log(ws, st, rows):
    for col, h in enumerate(("Dashboard", "Test Case ID", "Description of Change"), 1):
        c = ws.cell(row=1, column=col, value=h)
        c.font, c.fill, c.border = st["font"](bold=True), st["hdr_fill"], st["border"]
    for col, w in (("A", 30), ("B", 26), ("C", 70)):
        ws.column_dimensions[col].width = w
    for r, (dash, tid, desc) in enumerate(rows, 2):
        for col, v in enumerate((dash, tid, desc), 1):
            c = ws.cell(row=r, column=col, value=v)
            c.font, c.border, c.alignment = st["font"](), st["border"], st["top"]


def render_xlsx(tcs, title, xlsx_path, concepts=None, manifest=None,
                test_type="SIT", draft=False, grade=None, changes=None,
                change_log=True):
    """Render the SIT workbook (template: tools/reference-format-sit.xlsx).
    `change_log=False` (suite compiles: a selection, not a scope delivery)
    leaves the Change Log sheet with its header row only."""
    from openpyxl import Workbook
    concepts = concepts or {}
    manifest = manifest or {}
    cfg = load_config()
    exp = cfg.get("export") or {}
    st = _styles()
    groups = _group(tcs, concepts)

    tc_sheet_names = [_sheet_name(mod_fm, i) for i, (_r, mod_fm, _s) in enumerate(groups)]
    prefix = exp.get("module_prefix")
    module_name = _plain(" / ".join(
        f"{prefix} - {(mfm or {}).get('title', '?')}" if prefix
        else (mfm or {}).get("title", "?") for _r, mfm, _s in groups) or title)
    meta = dict(
        module_name=module_name,
        test_type=test_type,
        version=f"v{cfg.get('project', {}).get('okf_version', '0.1')}",
        date=date.today().strftime("%d %b %Y"),
        prepared_date=datetime.now().strftime("%d %b %Y, %H:%M"),
        tabs=[("A - Table of Contents", "Table of Contents"),
              ("B - Proj Doc References", "Project Document References")]
             + [(n, "Test Case") for n in tc_sheet_names]
             + [("Test Statistics", "Test Statistics"),
                ("Change Log", "Change Log")],
        docs=[("PRD", f"{cfg.get('project', {}).get('name', '')} - "
                      f"PRD v{manifest.get('adopted_prd_version', '?')}")],
    )
    if draft:
        meta.update(version="DRAFT r0", title_prefix="DRAFT (ungraded, round 0) - ",
                    revision_summary=("DRAFT first cut - rendered and sealed, not yet "
                                      "graded against the ISO/IEC/IEEE 29119-4 rubric. "
                                      "A final workbook with a Change Log follows."))
    elif grade:
        meta.update(version=f"r{grade['round']} · rubric {grade['score']}",
                    revision_summary=(f"Graded round {grade['round']}: score "
                                      f"{grade['score']} (threshold {grade['threshold']}), "
                                      f"rubric {grade['version']}"))

    wb = Workbook()
    # pinned doc properties: identical inputs -> byte-identical workbook
    wb.properties.creator = "tc-copilot"
    wb.properties.created = wb.properties.modified = datetime(2026, 1, 1)
    _fill_toc(wb.active, exp, meta, st)
    wb.active.title = "A - Table of Contents"
    _fill_refs(wb.create_sheet("B - Proj Doc References"), meta, st)
    dashboards = []
    for i, (_mrel, mod_fm, subs) in enumerate(groups):
        ws = wb.create_sheet(tc_sheet_names[i])
        _fill_tc_sheet(ws, mod_fm, subs, concepts, exp, st)
        for _srel, sfm, tcl in subs:
            dashboards.append((_plain((sfm or {}).get("title") or title),
                               tc_sheet_names[i],
                               [_display_id(fm) for _r, fm, _b in tcl]))
    _fill_stats(wb.create_sheet("Test Statistics"), dashboards, st)
    dash_of = {}
    for _mrel, _mod_fm, subs in groups:
        for _srel, sfm, tcl in subs:
            for _r, fm, _b in tcl:
                dash_of[_display_id(fm)] = _plain((sfm or {}).get("title") or title)
    _fill_change_log(wb.create_sheet("Change Log"), st,
                     change_rows(changes, dash_of, draft=draft) if change_log else [])
    wb.save(xlsx_path)


def inventory_paths(name, kind):
    """Timestamped xlsx/md paths under build/inventory/<kind>/, plus the
    stable '-latest' copies scripts/smoke/COM snippets read from.
    Returns (outdir, xlsx_ts, md_ts, xlsx_latest, md_latest)."""
    outdir = ROOT / "build/inventory" / kind
    outdir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    xlsx_ts = outdir / f"{name}_{ts}.xlsx"
    md_ts = outdir / f"{name}_{ts}.md"
    xlsx_latest = outdir / f"{name}-latest.xlsx"
    md_latest = outdir / f"{name}-latest.md"
    return outdir, xlsx_ts, md_ts, xlsx_latest, md_latest


def compile_suite(name, graph=False):
    import shutil
    spath = ROOT / "suites" / f"{name}.yaml"
    if not spath.exists():
        sys.exit(f"suite compile: suites/{name}.yaml not found")
    from wiki import refuse_if_unsealed
    refuse_if_unsealed(f"suite compile {name}")
    suite = yaml.safe_load(spath.read_text(encoding="utf-8"))
    concepts, manifest = load_all()
    selected, retired, stale = select(suite, concepts)

    title = f"Suite: {name}"
    kind = suite.get("kind", "sit")
    outdir, xlsx_ts, md_ts, xlsx_latest, md_latest = inventory_paths(name, kind)
    render_xlsx(selected, title, xlsx_ts, concepts=concepts,
                manifest=manifest,
                test_type={"mixed": "SIT+UAT"}.get(kind, kind.upper()),
                change_log=False)
    shutil.copyfile(xlsx_ts, xlsx_latest)

    md = [HEADER, f"# Inventory: {name}", "",
          f"- kind: {suite.get('kind')} · PRD v{manifest.get('adopted_prd_version')} "
          f"· active TCs: {len(selected)}",
          f"- filters: include_modules={suite.get('include_modules') or 'all'}, "
          f"exclude_modules={suite.get('exclude_modules') or []}, "
          f"priorities={suite.get('priorities') or 'all'}", ""]
    for _rel, fm, _b in selected:
        md.append(f"- **{fm['id']}** [{fm.get('priority')}/{fm.get('technique')}] - "
                  f"{fm['title']}")
    if stale:
        md += ["", "## Stale (excluded - pending human decision)", ""]
        md += [f"- {fm['id']} - stale_because: "
               f"{[c['cause'] for c in fm.get('stale_because') or []]}"
               for _r, fm, _b in stale]
    md += ["", "## Retired (never deleted - spec §13.4)", ""]
    md += ([f"- {fm['id']} - {(fm.get('retirement') or {}).get('reason', '?')}"
            for _r, fm, _b in retired] or ["_None._"])
    md.append("")
    md_text = "\n".join(md)
    md_ts.write_text(md_text, encoding="utf-8", newline="\n")
    shutil.copyfile(md_ts, md_latest)
    rel_ts = xlsx_ts.relative_to(ROOT).as_posix()
    print(f"suite {name}: {len(selected)} active, {len(stale)} stale (excluded), "
          f"{len(retired)} retired -> {rel_ts} (+ {xlsx_latest.name})")

    from wiki_graph import build_model, emit, scope_suite
    model = build_model(concepts, manifest)
    tc_rels = [rel for rel, _fm, _body in selected]
    emit(f"suite-{name}", scope_suite(model, tc_rels, name), make_html=graph)


def cmd_suite(args):
    if not args:
        sys.exit("usage: wiki suite compile <name>")
    if args[0] == "compile":
        compile_suite(args[1], graph="--graph" in args)
    else:
        sys.exit(f"unknown suite subcommand {args[0]} (NL authoring is the "
                 "tc-suite-author skill; the YAML is the artifact of record)")
