#!/usr/bin/env python3
"""RTM compiler (tc-copilot-spec §11.3): one traversal, three renders.

  build/rtm/matrix.md   AC × TC coverage matrix (retired appendix, voided struck)
  build/rtm/trace.md    TC -> AC -> story -> PRD §/Figma chain (reverse read)
  build/rtm/graph.json  D3 force-graph contract {nodes:[{id,type,state}],links:[...]}
  build/rtm/gaps.md     uncovered ACs, orphan TCs, stale pins, unaligned-flow members

Deterministic, LLM-free. Reads concepts + manifest only; writes only build/rtm/.
"""
import json
from pathlib import Path

from wiki import ROOT, load_all, load_manifest, resolve_ref
from wiki_coverage import components_covering, load_coverage
from wiki_graph import build_model, collect

HEADER = "<!-- generated by wiki rtm — reproducible from manifest + wiki; do not edit -->\n"


def build_matrix(stories, tcs, modules, coverage, manifest):
    lines = [HEADER, "# Requirements Traceability Matrix", "",
             f"PRD version: {manifest.get('adopted_prd_version')}"
             + (f" (v{manifest['staged_prd_version']} staged, not adopted)"
                if manifest.get("staged_prd_version") else ""), ""]
    by_module = {}
    for rel, fm in stories.items():
        mod = resolve_ref(fm.get("module") or "")[0] if fm.get("module") else "(none)"
        by_module.setdefault(mod, []).append((rel, fm))
    retired_rows = []
    for mod in sorted(by_module):
        mfm = modules.get(mod)
        lines += [f"## Module: {mfm['title'] if mfm else mod}", ""]
        for rel, fm in sorted(by_module[mod]):
            acs = fm.get("acceptance_criteria") or []
            if not acs:
                lines += [f"### {fm['id']} — {fm['title']} ({fm.get('status')})",
                          "", "_No acceptance criteria (story not yet aligned)._", ""]
                continue
            lines += [f"### {fm['id']} — {fm['title']} ({fm.get('status')})", "",
                      "| AC | Status | Covered by (active) | Coverage |",
                      "|---|---|---|---|"]
            for ac in acs:
                ref = f"{rel}#{ac['id']}"
                cov = coverage.get(ref, [])
                active = [t[1]["id"] for t in cov if t[1].get("status") == "active"]
                stale = [t[1]["id"] for t in cov if t[1].get("status") == "stale"]
                retired_rows += [(t[1], ref) for t in cov
                                 if t[1].get("status") == "retired"]
                if ac.get("status") == "voided":
                    cause = (ac.get("voided") or {}).get("caused_by", "?")
                    lines.append(f"| ~~{ac['id']}~~ | voided ({cause}) | — | voided |")
                    continue
                cell = ", ".join(active) or "—"
                if stale:
                    cell += f" (+stale: {', '.join(stale)})"
                state = "covered" if active else ("STALE-ONLY" if stale else "GAP")
                lines.append(f"| {ac['id']} | active | {cell} | {state} |")
            lines.append("")
            cmap, disp, cstatus = load_coverage(fm)
            comps = fm.get("components") or []
            if comps:
                lines += [f"#### Component coverage ({cstatus or 'no map'})", "",
                          "| Component | ACs | Active TCs | State |",
                          "|---|---|---|---|"]
                for c in comps:
                    covering = components_covering(cmap, c["id"])
                    tcs_active = []
                    for a in covering:
                        for t_rel, t_fm in coverage.get(f"{rel}#{a}", []):
                            if t_fm.get("status") == "active":
                                tcs_active.append(t_fm["id"])
                    if covering and tcs_active:
                        state = "covered"
                    elif covering:
                        state = "ACs-without-TCs"
                    elif c["id"] in disp:
                        state = "out-of-scope"
                    else:
                        state = "GAP"
                    lines.append(
                        f"| {c['id']} {c.get('name', '')} | "
                        f"{', '.join(covering) or '—'} | "
                        f"{len(set(tcs_active))} | {state} |")
                unmapped = [a['id'] for a in fm.get('acceptance_criteria') or []
                            if cmap and not cmap.get(a['id'])]
                if unmapped:
                    lines.append(f"| _(unmapped ACs)_ | {', '.join(unmapped)} "
                                 f"| — | unmapped |")
                lines.append("")
    seen = set()
    uniq = [(fm, ref) for fm, ref in retired_rows
            if not (fm["id"] in seen or seen.add(fm["id"]))]
    lines += ["## Retired test cases", ""]
    if uniq:
        lines += ["| TC | Reason | Cause / Successor | Asserted by |", "|---|---|---|---|"]
        for fm, _ref in uniq:
            r = fm.get("retirement") or {}
            link = r.get("superseded_by") or \
                f"{r.get('caused_by', '?')} v{r.get('cause_version', '?')}"
            lines.append(f"| {fm['id']} | {r.get('reason', '?')} | {link} | "
                         f"{r.get('asserted_by', '?')} |")
    else:
        lines.append("_None._")
    lines.append("")
    return "\n".join(lines)


def build_trace(stories, tcs, flows, manifest):
    """TC -> source chain: the reverse read of matrix.md (which goes AC -> TC).

    Each row walks TC -covers-> AC -> Story -derived_from-> PRD section(s),
    so a tester can answer "what requirement is this test case for?" without
    opening the wiki. UAT TCs also cover a flow's journey fragments, so flows
    are resolved alongside stories.
    """
    owners = {**stories, **flows}
    prd_of, figma_of = {}, {}
    for rel, fm in owners.items():
        prd_of[rel] = [resolve_ref(r)[0] for r in fm.get("derived_from") or []]
        figma_of[rel] = [resolve_ref(r)[0] for r in fm.get("illustrated_by") or []]
    lines = [HEADER, "# Test Case -> Source Trace", "",
             f"PRD version: {manifest.get('adopted_prd_version')}", "",
             "| TC | Status | Covers AC | Story / Flow | PRD section(s) | Figma |",
             "|---|---|---|---|---|---|"]
    for rel, fm in sorted(tcs.items(), key=lambda kv: kv[1]["id"]):
        acs, srels = [], []
        for c in fm.get("covers") or []:
            tgt, frag = resolve_ref(c)
            acs.append(frag)
            if tgt not in srels:
                srels.append(tgt)
        story = ", ".join((owners.get(s) or {}).get("id", s.rsplit("/", 1)[-1])
                          for s in srels) or "—"
        prd = sorted({p for s in srels for p in prd_of.get(s, [])})
        figma = sorted({f for s in srels for f in figma_of.get(s, [])})
        lines.append(
            f"| {fm['id']} | {fm.get('status')} | {', '.join(acs) or '—'} | {story} "
            f"| {', '.join(p.rsplit('/', 1)[-1] for p in prd) or '—'} "
            f"| {', '.join(f.rsplit('/', 1)[-1] for f in figma) or '—'} |")
    lines.append("")
    return "\n".join(lines)


def build_gaps(stories, tcs, flows, coverage, manifest):
    lines = [HEADER, "# Gap Report", ""]
    gaps = []
    for rel, fm in stories.items():
        for ac in fm.get("acceptance_criteria") or []:
            if ac.get("status") == "voided":
                continue
            cov = coverage.get(f"{rel}#{ac['id']}", [])
            if not any(t[1].get("status") == "active" for t in cov):
                gaps.append(f"- `{rel}#{ac['id']}` — no active covering TC")
    lines += ["## Active ACs with zero active covering TCs", ""]
    lines += gaps or ["_None — full coverage._"]
    lines += ["", "## Orphan TCs (empty covers)", ""]
    orphans = [f"- {fm['id']}" for _rel, fm in tcs.items() if not fm.get("covers")]
    lines += orphans or ["_None._"]
    lines += ["", "## TCs pinned to a non-adopted PRD version", ""]
    adopted = manifest.get("adopted_prd_version")
    pinned = [f"- {fm['id']} (pinned v{(fm.get('generated_from') or {}).get('prd_version')})"
              for _rel, fm in tcs.items()
              if (fm.get("generated_from") or {}).get("prd_version") not in (None, adopted)]
    lines += pinned or ["_None._"]
    lines += ["", "## Flows containing unaligned stories", ""]
    bad_flows = []
    for rel, fm in flows.items():
        for sref in fm.get("stories") or []:
            tgt, _ = resolve_ref(sref)
            sfm = stories.get(tgt)
            if sfm and sfm.get("status") != "aligned":
                bad_flows.append(f"- {fm['id']}: member {sref} is "
                                 f"'{sfm.get('status')}'")
    lines += bad_flows or ["_None._"]
    lines += ["", "## Components without AC coverage (undispositioned)", ""]
    comp_gaps = []
    for rel, fm in stories.items():
        cmap, disp, _cs = load_coverage(fm)
        for c in fm.get("components") or []:
            covering = components_covering(cmap, c["id"])
            if not covering and c["id"] not in disp:
                comp_gaps.append(f"- {rel}#{c['id']} — {c.get('name', '')}")
    lines += comp_gaps or ["_None._"]
    lines += ["", "## Components whose ACs have no active TCs", ""]
    dead = []
    for rel, fm in stories.items():
        cmap, _disp, _cs = load_coverage(fm)
        for c in fm.get("components") or []:
            covering = components_covering(cmap, c["id"])
            if covering and not any(
                    t[1].get("status") == "active"
                    for a in covering for t in coverage.get(f"{rel}#{a}", [])):
                dead.append(f"- {rel}#{c['id']} — ACs {covering} have no active TC")
    lines += dead or ["_None._"]
    lines.append("")
    return "\n".join(lines), len(gaps), len(orphans), len(pinned), len(comp_gaps)


def cmd_rtm(args=None):
    concepts, manifest = load_all()
    stripped = {rel: (fm, body, p) for rel, (fm, body, p) in concepts.items()}
    (stories, tcs, flows, terms, prd, figma, modules, resolutions,
     coverage) = collect(stripped, manifest)
    outdir = ROOT / "build/rtm"
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "matrix.md").write_text(
        build_matrix(stories, tcs, modules, coverage, manifest),
        encoding="utf-8", newline="\n")
    graph = build_model(concepts, manifest)
    (outdir / "graph.json").write_text(json.dumps(graph, indent=1, ensure_ascii=False),
                                       encoding="utf-8", newline="\n")
    (outdir / "trace.md").write_text(
        build_trace(stories, tcs, flows, manifest),
        encoding="utf-8", newline="\n")
    gaps_md, ngaps, norph, npin, ncomp = build_gaps(stories, tcs, flows, coverage, manifest)
    (outdir / "gaps.md").write_text(gaps_md, encoding="utf-8", newline="\n")
    print(f"rtm: matrix ({len(stories)} stories), trace ({len(tcs)} TCs), graph "
          f"({graph['meta']['counts']['nodes']} nodes / "
          f"{graph['meta']['counts']['links']} links), gaps "
          f"({ngaps} uncovered ACs, {norph} orphans, {npin} version-pinned, "
          f"{ncomp} component gaps)")
    from wiki_graph import (emit, scope_rtm, scope_traceability,
                            RTM_PRESETS, TRACE_PRESETS, TRACE_DESC)
    html = bool(args and "--graph" in args)
    # traceability: the clean, module-anchored PRD -> Story -> AC -> TC tree.
    emit("traceability", scope_traceability(graph), make_html=html,
         title="tc-copilot Traceability", description=TRACE_DESC,
         presets=TRACE_PRESETS)
    # rtm: the full graph (every node/edge), with lens presets to focus it.
    emit("rtm", scope_rtm(graph), make_html=html, presets=RTM_PRESETS)
