#!/usr/bin/env python3
"""Suites (tc-copilot-spec §9): selection, never generation.

`wiki suite compile <name>` filters ACTIVE TCs from the wiki per
suites/<name>.yaml and writes build/inventory/<name>.md + .xlsx.
Zero LLM calls, zero writes outside build/ (spec P7, acceptance test 3).
Retired TCs render in a separate section; stale TCs are listed but flagged.
"""
import math
import re
import sys
from datetime import date, datetime
from pathlib import Path

import yaml

from wiki import (ROOT, adopted_version, body_section, load_all, load_config,
                  load_manifest, now_iso, prd_registry, resolve_ref)
from wiki_coverage import ELEMENT_BLOCK_LEAD

HEADER = "<!-- generated by wiki suite compile — reproducible from manifest + wiki; do not edit -->\n"


def tc_sort_key(fm):
    # A TC covering a flow journey fragment (#J\d+) sorts by journey position
    # ahead of everything, so UAT sheets read in walk order (module key "" wins).
    for ref in fm.get("covers") or []:
        rel, frag = resolve_ref(ref)
        if rel.startswith("flows/") and frag and re.match(r"^J\d+$", frag):
            # The journey's walk order when the renderer recorded it (`order`),
            # so an entry inserted mid-journey sits where it runs; the journey
            # number for test cases rendered before `order` existed.
            pos = fm["order"] if isinstance(fm.get("order"), int) else int(frag[1:])
            return ("", (), 0, pos, fm["id"])
    m = re.match(r"^(?:UAT-)?(\d[\d.]*)-AC(\d+)-(\d+)$", fm["id"])
    if not m:
        return (fm.get("module") or "", (), 999, 999, fm["id"])
    prefix = tuple(int(p) for p in m.group(1).split("."))
    if isinstance(fm.get("order"), int):
        # Flow order (tc-style R6): the spec's run order, so a section's test
        # cases read top-down as one chain rather than AC-number order.
        return (fm.get("module") or "", prefix, 0, fm["order"], fm["id"])
    return (fm.get("module") or "", prefix, int(m.group(2)), int(m.group(3)),
            fm["id"])


def tc_prds(fm):
    """The PRD ids a test case draws on: the keys of its
    generated_from.prd_versions. An old-form test case (prd_version only)
    draws on none."""
    return set((fm.get("generated_from") or {}).get("prd_versions") or {})


def check_prd_filters(suite, manifest):
    """include_prds / exclude_prds must name registered PRDs. A typo would
    otherwise select nothing (or exclude nothing) without a word."""
    reg = prd_registry(manifest)
    for key in ("include_prds", "exclude_prds"):
        vals = suite.get(key) or []
        if not isinstance(vals, list):
            raise ValueError(f"{key} must be a list of PRD ids, got {vals!r}")
        # A mapping or a list as an element is unhashable: `v not in reg`
        # would raise instead of refusing.
        bad = [v for v in vals if not isinstance(v, str) or v not in reg]
        if bad:
            raise ValueError(
                f"{key} names unknown PRD id(s) {bad}; registered: "
                f"{', '.join(sorted(reg)) or '(none)'}")


def prd_names(tcs, manifest):
    """'<title> - v<adopted>' for every PRD the given test cases draw on,
    sorted by PRD id. Never 'vNone' (wiki.prd_version_text's policy): a PRD
    with nothing adopted says so, and an id the registry does not hold is
    named as unregistered."""
    reg = prd_registry(manifest)
    ids = sorted({pid for _r, fm, _b in tcs for pid in tc_prds(fm)})

    def name(pid):
        if pid not in reg:
            return f"{pid} (unregistered)"
        v = adopted_version(manifest, pid)
        return (f"{reg[pid].get('title') or pid} - "
                + (f"v{v}" if v is not None else "no adopted version"))
    return [name(pid) for pid in ids]


def prd_docs(tcs, manifest, project_name):
    """Rows of the Proj Doc References sheet: one per PRD the selected test
    cases draw on; with none, a single row naming the project, no version."""
    return ([("PRD", n) for n in prd_names(tcs, manifest)]
            or [("PRD", project_name)])


def select(suite, concepts):
    """Returns (selected, retired, stale_included) lists of (rel, fm, body)."""
    kind = suite.get("kind", "sit")
    inc_mod = suite.get("include_modules") or []
    exc_mod = suite.get("exclude_modules") or []
    inc_flow = suite.get("include_flows") or []
    exc_flow = suite.get("exclude_flows") or []
    inc_prd = set(suite.get("include_prds") or [])
    exc_prd = set(suite.get("exclude_prds") or [])
    prios = suite.get("priorities") or []
    extra_inc = set(suite.get("extra_include") or [])
    extra_exc = set(suite.get("extra_exclude") or [])

    selected, retired, stale = [], [], []
    for rel, (fm, body, _p) in sorted(concepts.items()):
        if not fm or fm.get("type") != "Test Case":
            continue
        if kind != "mixed" and fm.get("kind") != kind:
            continue
        mod = Path(resolve_ref(fm["module"])[0]).name if fm.get("module") else None
        flow = Path(resolve_ref(fm["flow"])[0]).name if fm.get("flow") else None
        in_scope = True
        if inc_mod and (mod not in inc_mod):
            in_scope = False
        if mod in exc_mod:
            in_scope = False
        if inc_flow and (flow not in inc_flow):
            in_scope = False
        if flow in exc_flow:
            in_scope = False
        prds = tc_prds(fm)
        if inc_prd and not (prds & inc_prd):
            in_scope = False
        if prds & exc_prd:
            in_scope = False
        if prios and fm.get("priority") not in prios:
            in_scope = False
        if fm["id"] in extra_inc:
            in_scope = True
        if fm["id"] in extra_exc:          # subtractive wins (spec §9)
            in_scope = False
        if not in_scope:
            continue
        st = fm.get("status")
        if st == "active":
            selected.append((rel, fm, body))
        elif st == "retired":
            retired.append((rel, fm, body))
        elif st == "stale":
            stale.append((rel, fm, body))
    keyf = lambda t: tc_sort_key(t[1])
    return sorted(selected, key=keyf), sorted(retired, key=keyf), sorted(stale, key=keyf)


# ------------------------------------------------------------------ xlsx
# SIT workbook format (template: tools/reference-format-sit.xlsx = the
# reference SIT workbook layout, a synthetic example generated by
# tools/make_reference_workbooks.py). Five sheets:
#   A - Table of Contents · B - Proj Doc References · one C-TC-<sec> sheet
#   per module · Test Statistics · Change Log
# TC sheet columns A-L; F-L are execution columns left blank for testers.

TC_COLS = ("Test Case ID", "Scenario", "Test Steps", "Field / Values",
           "Expected Results", "Confidence", "Remarks",
           "Actual Results", "Status", "Tested by",
           "Date Tested", "Retested by", "Retested Date", "Remarks")
COL_W = dict(zip("ABCDEFGHIJKLMN",
                 (26, 66, 51, 31, 66, 14, 56, 26, 16, 12, 12, 12, 13, 20)))
STATUSES = ("Pass", "Fail", "Block", "Void", "Not Yet Tested", "Pending Retest")
# Review aids sit directly after Expected Results (F, G): the tester reads the
# test case, then how far each part of it is grounded in the source. The
# execution grid follows (H-N); Status is column I = index STATUS_COL.
N_AUTHORED = 7          # A-G are authored; H onward is filled during execution
STATUS_COL = 9
CONF_PARTS = (("scenario", "Scenario"), ("steps", "Test Steps"),
              ("data", "Field / Values"), ("expected", "Expected Results"))
CONF_FILL = {"High": "C6EFCE", "Medium": "FFEB9C", "Low": "FFC7CE"}
# Precondition lines that state where a test case starts (tc-style R6). The
# export lifts them to the top of the Test Steps cell.
CHAIN_PREFIXES = ("Continue from TC-", "Start of run:")
# `# Test Data` placeholders that mean "nothing to enter": an empty cell.
BLANK_DATA = ("-", "N/A", "_None_")
LAST_COL = len(TC_COLS)
TC_HEADER_ROW = 8      # header row on every C-TC sheet; Status is column I
STATS_FIRST_ID_ROW = 22


def _styles():
    from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
    thin = Side(style="thin")
    return dict(
        border=Border(left=thin, right=thin, top=thin, bottom=thin),
        hdr_fill=PatternFill("solid", fgColor="D9D9D9"),
        exec_fill=PatternFill("solid", fgColor="92D050"),
        sect_fill=PatternFill("solid", fgColor="BFBFBF"),
        flow_fill=PatternFill("solid", fgColor="DDEBF7"),
        conf_fill={k: PatternFill("solid", fgColor=v)
                   for k, v in CONF_FILL.items()},
        top=Alignment(wrap_text=True, vertical="top"),
        center=Alignment(wrap_text=True, vertical="center", horizontal="center"),
        font=lambda **kw: Font(name="Arial", **{"size": 10, **kw}),
        blue=Font(name="Arial", size=10, bold=True, color="0070C0"),
    )


def _confidence_remarks(fm, qmap=None):
    """The Remarks cell: one `**Column**: Level - remark` line per reviewed
    column (tc-style R7). Falls back to a single remark for a test case
    rendered before confidence was rated per part. `qmap` maps a doubt id
    (`<scenario_id>#<part>`) to its question id, shown as `Level [Q-...]`."""
    qmap = qmap or {}
    parts = fm.get("confidence_parts")
    if isinstance(parts, dict) and parts:
        lines = []
        for key, label in CONF_PARTS:
            p = parts.get(key) or {}
            if p.get("level"):
                remark = str(p.get("remark") or "").strip() or "stated by the source."
                qid = qmap.get(f"{fm.get('scenario_id')}#{key}")
                tag = f" [{qid}]" if qid else ""
                lines.append(f"**{label}**: {p['level']}{tag} - {remark}")
        return "\n".join(lines)
    return str(fm.get("confidence_remarks") or "")


def _fm_of(concepts, rel):
    c = concepts.get(rel)
    return c[0] if c else None


# tc-style contract (skill .claude/skills/tc-style): workbook text uses
# hyphens (never em/en dashes) and renders `**...**` markers as real bold.
_DASHES = {0x2014: "-", 0x2013: "-"}
_BOLD_RE = re.compile(r"\*\*(.+?)\*\*", re.DOTALL)


def _plain(text):
    """Marker-free, dash-normalized text (for height estimation / md output)."""
    return _BOLD_RE.sub(r"\1", str(text).translate(_DASHES))


def _richify(text):
    """Cell value per tc-style: em/en dashes -> hyphens; '**...**' markers ->
    rich-text bold runs. Returns a plain str when nothing is bold."""
    s = str(text).translate(_DASHES)
    if "**" not in s:
        return s
    from openpyxl.cell.rich_text import CellRichText, TextBlock
    from openpyxl.cell.text import InlineFont
    bold = InlineFont(rFont="Arial", sz=10, b=True)
    rich = CellRichText()
    for i, part in enumerate(_BOLD_RE.split(s)):
        if part:
            rich.append(TextBlock(bold, part) if i % 2 else part)
    return rich


def _display_id(fm):
    # Org sheets prefix ids with "TC-" (e.g. TC-1.1.3.1.1-AC1-01); the sheet's
    # Total-TC COUNTIF and the Test Statistics VLOOKUPs key off this form.
    # UAT ids carry a "UAT-" prefix in the wiki; strip it to the org "TC-" form.
    tid = fm["id"]
    if tid.startswith("UAT-"):
        return "TC-" + tid[4:]
    return tid if tid.startswith(("TC-", "BR-")) else f"TC-{tid}"


def _ac_text(fm, concepts):
    for ref in fm.get("covers") or []:
        rel, frag = resolve_ref(ref)
        sfm = _fm_of(concepts, rel)
        if not (sfm and frag):
            continue
        for key in ("acceptance_criteria", "branches"):
            for ac in sfm.get(key) or []:
                if ac.get("id") == frag:
                    return ac.get("text") or ""
    return ""


def _scenario_cell(fm, body, concepts):
    """Template Scenario column: 'Scenario/Given/When/Then' parsed from the
    covered AC's Gherkin-in-prose text; falls back to the TC objective."""
    text = " ".join(_ac_text(fm, concepts).split())
    m = re.match(r"^(?P<t>.+?\.)\s+Given (?P<g>.+?), when (?P<w>.+?), then (?P<n>.+)$",
                 text, re.IGNORECASE)
    if m:
        g, w, n = (m.group(k).rstrip(".") for k in "gwn")
        return (f"**Scenario:** {m.group('t')}\n\n**Given:** {g[:1].upper()}{g[1:]}.\n\n"
                f"**When:** {w[:1].upper()}{w[1:]}.\n\n**Then:** {n[:1].upper()}{n[1:]}.")
    obj = body_section(body, "Objective") or fm.get("description") or ""
    return f"**Scenario:** {fm['title']}.\n\n{obj}".strip()


def _precond_lines(body):
    sec = body_section(body, "Preconditions") or ""
    return [re.sub(r"^\d+\.\s*", "", ln.strip())
            for ln in sec.splitlines() if ln.strip()]


def _subgroup_of(fm, concepts):
    """(rel, fm) of the first covering story; falls back to the flow.

    Story-from-covers is tried FIRST so UAT sheets (whose TCs carry a `flow`
    but cover a story AC) group by screen (the member story) rather than
    collapsing every UAT TC under the single flow."""
    for ref in fm.get("covers") or []:
        rel, _frag = resolve_ref(ref)
        sfm = _fm_of(concepts, rel)
        if sfm and sfm.get("type") == "User Story":
            return rel, sfm
    if fm.get("flow"):
        rel = resolve_ref(fm["flow"])[0]
        return rel, _fm_of(concepts, rel)
    return None, None


def _group(tcs, concepts):
    """[(mod_rel, mod_fm, [(sub_rel, sub_fm, [tc, ...]), ...]), ...]
    Modules and subgroups keep first-TC order (tcs arrive sorted)."""
    mods, order = {}, []
    for rel, fm, body in tcs:
        mrel = resolve_ref(fm.get("module") or fm.get("flow") or "unassigned")[0]
        if mrel not in mods:
            mods[mrel] = {}
            order.append(mrel)
        srel, sfm = _subgroup_of(fm, concepts)
        mods[mrel].setdefault(srel, (sfm, []))[1].append((rel, fm, body))
    return [(mrel, _fm_of(concepts, mrel),
             [(srel, sfm, tcl) for srel, (sfm, tcl) in mods[mrel].items()])
            for mrel in order]


def _sheet_name(mod_fm, idx):
    desc = (mod_fm or {}).get("description") or ""
    m = re.search(r"§(\d+(?:\.\d+)*)", desc)
    sec = m.group(1) if m else str(idx + 1)
    title = _plain((mod_fm or {}).get("title") or "Test Cases")
    name = f"C-TC-{sec} ({title})"
    while len(name) > 31:                    # Excel sheet-name hard limit
        words = title.split()
        i = max(range(len(words)), key=lambda j: len(words[j]))
        if len(words[i]) <= 4:
            title = title[:len(title) - (len(name) - 31)].rstrip()
            name = f"C-TC-{sec} ({title})"
            break
        words[i] = words[i][:4]
        title = " ".join(words)
        name = f"C-TC-{sec} ({title})"
    return re.sub(r"[\[\]:*?/\\']", "-", name)


def run_groups(tcs):
    """[(run_name, [tc, ...])] in first-appearance order. A run is one complete
    flow and gets its own worksheet (tc-style R6). Test cases with no `run`
    share one group (name ""), so a set rendered before runs existed keeps one
    sheet."""
    order, groups = [], {}
    for tc in tcs:
        name = tc[1].get("run") or ""
        if name not in groups:
            groups[name] = []
            order.append(name)
        groups[name].append(tc)
    return [(n, groups[n]) for n in order]


def run_sheet_name(run_name, idx):
    """`C-TC-<n> (<run>)`, cut to Excel's 31 characters, with the characters
    Excel forbids in a sheet name replaced by a hyphen. The `<n>` prefix is the
    run's index, so two runs never share a name even when their titles
    truncate to the same text."""
    base = f"C-TC-{idx + 1} ("
    room = 31 - len(base) - 1
    title = _plain(run_name)[:room].rstrip() or "Run"
    return re.sub(r"[\[\]:*?/\\']", "-", f"{base}{title})")


def sheet_common(tcs):
    """Pre-condition lines every test case of one sheet shares: the sheet's
    blue <Pre-condition> block. A chain line is never a shared pre-condition:
    it leads each case's Test Steps (an all-start sheet repeats the same line
    in every case)."""
    pre_lists = [_precond_lines(b) for _r, _f, b in tcs]
    return [ln for ln in (pre_lists[0] if pre_lists else [])
            if not ln.startswith(CHAIN_PREFIXES)
            and all(ln in pl for pl in pre_lists[1:])]


def tc_cells(fm, body, concepts, common, qmap=None):
    """The authored cells of one test-case row, as text that still carries its
    `**bold**` markers. `_fill_tc_sheet` writes exactly these values and the
    operator app's grid reads them through the same call, so the sheet and
    the grid cannot diverge. `chain` and `extra` are the pre-condition lines
    the row lifts into Test Steps and Field / Values."""
    data = body_section(body, "Test Data") or ""
    if data.strip() in BLANK_DATA:
        data = ""
    extra = [ln for ln in _precond_lines(body) if ln not in common]
    chain = [ln for ln in extra if ln.startswith(CHAIN_PREFIXES)]
    extra = [ln for ln in extra if not ln.startswith(CHAIN_PREFIXES)]
    if extra:
        # tc-style R5: TC-specific setup appends as bare lines - no
        # "Pre-condition:" label, no numbering (shared lines live in
        # the sheet's blue <Pre-condition> block).
        lines = "\n".join(extra)
        data = f"{data}\n\n{lines}".strip() if data else lines
    steps = body_section(body, "Steps") or ""
    if chain:
        # "Continue from TC-..." leads the steps, then the flow starts
        steps = "\n".join(chain) + "\n\n" + steps
    return {"id": _display_id(fm),
            "scenario": _scenario_cell(fm, body, concepts),
            "steps": steps, "data": data,
            "expected": body_section(body, "Expected Results") or "",
            "confidence": fm.get("confidence") or "",
            "remarks": _confidence_remarks(fm, qmap),
            "chain": chain, "extra": extra}


_ELEMENT_ITEM_RE = re.compile(rf"(?m)^\d+\. {re.escape(ELEMENT_BLOCK_LEAD)}$")


def split_expected(text):
    """(own items, element block) of an Expected Results text. The renderers
    append the element-verification block as the last numbered item; it is
    derived from the story's coverage map, so the app shows it read-only
    beside the items a human may reword."""
    text = text or ""
    hits = list(_ELEMENT_ITEM_RE.finditer(text))
    if not hits:
        return text, ""
    at = hits[-1].start()
    return text[:at].rstrip("\n"), text[at:]


def plan_sheets(tcs, concepts):
    """[(sheet name, module fm, subs, dashboard title or None)] - the C-TC
    worksheets a selection becomes. One per run when test cases carry `run`;
    otherwise (UAT, older content) one per module. A run sheet keeps the
    module grouping inside it; test cases with no run (mixed selection) form
    one unnamed group that takes the module sheet's name."""
    sheets = []
    if any(fm.get("run") for _r, fm, _b in tcs):
        for ri, (run_name, rtcs) in enumerate(run_groups(tcs)):
            rg = _group(rtcs, concepts)
            subs = [sub for _m, _mf, ss in rg for sub in ss]
            if len(rg) == 1:
                mod_fm = rg[0][1]
            else:
                mod_fm = {"title": " / ".join(
                    (mf or {}).get("title", "?") for _m, mf, _s in rg)}
            name = (run_sheet_name(run_name, ri) if run_name
                    else _sheet_name(rg[0][1], ri))
            sheets.append((name, mod_fm, subs, run_name or None))
    else:
        for i, (_r, mod_fm, subs) in enumerate(_group(tcs, concepts)):
            sheets.append((_sheet_name(mod_fm, i), mod_fm, subs, None))
    return sheets


def _est_height(vals):
    lines = 1
    for col, val in zip("ABCDEFG", vals):
        if not val:
            continue
        w = max(COL_W[col] - 2, 10)
        n = sum(max(1, math.ceil(len(ln) / w)) for ln in _plain(val).split("\n"))
        lines = max(lines, n)
    return min(max(14 * lines, 20), 400)


def _fill_toc(ws, exp, meta, st):
    ws["B1"] = meta.get("title_prefix", "") + "AGILE TEST SPECIFICATIONS - Table of Contents"
    ws["B1"].font = st["font"](bold=True, size=14)
    rows = [(3, "Project Code", exp.get("project_code", "")),
            (4, "Project Name", exp.get("project_name", "")),
            (5, "System/Subsystem Name (if applicable)", exp.get("system_name", "")),
            (6, "Module Name (if applicable)", meta["module_name"]),
            (7, "Test Type", meta["test_type"]),
            (8, "Version No.", meta["version"]),
            (9, "Prepared by / Date",
             f"{(exp.get('prepared_by') or '').strip()} / {meta['prepared_date']}".strip()),
            (10, "Reviewed by / Date", ""),
            (12, "Test Execution Cycle", meta["test_type"]),
            (13, "Test Execution Period",
             "From <dd/mm/yyyy> to <dd/mm/yyyy> - to be filled during test execution"),
            (14, "Test Result As At", "<dd/mm/yyyy> - to be filled during test execution")]
    for r, label, val in rows:
        ws.cell(row=r, column=1, value=label).font = st["font"](bold=True)
        ws.cell(row=r, column=3, value=val).font = st["font"]()
    ws.cell(row=16, column=1, value="Revision History").font = st["font"](bold=True, size=12)
    for col, h in enumerate(("Version", "Effective Date", "Summary of Changes", "Author"), 1):
        c = ws.cell(row=17, column=col, value=h)
        c.font, c.fill, c.border = st["font"](bold=True), st["hdr_fill"], st["border"]
    for col, v in enumerate((meta["version"], meta["date"],
                             meta.get("revision_summary", "Generated by tc-copilot (wiki export)"),
                             (exp.get("prepared_by") or "").strip()), 1):
        c = ws.cell(row=18, column=col, value=v)
        c.font, c.border = st["font"](), st["border"]
    ws.cell(row=21, column=1, value="Table of Contents").font = st["font"](bold=True, size=12)
    for col, h in enumerate(("Tab", "Title"), 1):
        c = ws.cell(row=22, column=col, value=h)
        c.font, c.fill, c.border = st["font"](bold=True), st["hdr_fill"], st["border"]
    for i, (tab, tab_title) in enumerate(meta["tabs"]):
        for col, v in enumerate((tab, tab_title), 1):
            c = ws.cell(row=23 + i, column=col, value=v)
            c.font, c.border = st["font"](), st["border"]
    ws.column_dimensions["A"].width = 38
    ws.column_dimensions["B"].width = 22
    ws.column_dimensions["C"].width = 60
    ws.column_dimensions["D"].width = 22


def _fill_refs(ws, meta, st):
    ws["B1"] = "AGILE TEST SPECIFICATIONS\n- Project Document References"
    ws["B1"].font = st["font"](bold=True, size=14)
    ws["B1"].alignment = st["top"]
    labels = (("A3", "Project Code / Name",
               "=CONCATENATE('A - Table of Contents'!$C$3,\"/ \",'A - Table of Contents'!$C$4)"),
              ("A4", "System/Subsystem/Module",
               "=CONCATENATE('A - Table of Contents'!$C$5,\"/ \",'A - Table of Contents'!$C$6)"),
              ("A5", "Test Type / Version No.",
               "=CONCATENATE('A - Table of Contents'!$C$7,\"/ \",'A - Table of Contents'!$C$8)"))
    for coord, label, formula in labels:
        ws[coord] = label
        ws[coord].font = st["font"](bold=True)
        c = ws.cell(row=ws[coord].row, column=3, value=formula)
        c.font = st["font"]()
    for col, h in enumerate(("Document Type", "Document Name and version"), 1):
        c = ws.cell(row=7, column=1 if col == 1 else 3, value=h)
        c.font, c.fill, c.border = st["font"](bold=True), st["hdr_fill"], st["border"]
    for i, (dtype, dname) in enumerate(meta["docs"]):
        a = ws.cell(row=8 + i, column=1, value=dtype)
        b = ws.cell(row=8 + i, column=3, value=dname)
        a.font = b.font = st["font"]()
        a.border = b.border = st["border"]
    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["C"].width = 70


def _fill_tc_sheet(ws, mod_fm, subs, concepts, exp, st, qmap=None):
    ws["B2"] = "AGILE TEST SPECIFICATIONS - Test Cases"
    ws["B2"].font = st["font"](bold=True, size=12)
    ws["C3"] = '=CONCATENATE("Total TC = ",COUNTIF(A:A,"TC-*")+COUNTIF(A:A,"BR-*"))'
    ws["C3"].font = st["font"](bold=True)
    for r, label in ((4, "Project Code / Name"), (5, "System/Subsystem/Module"),
                     (6, "Test Type / Version No.")):
        ws.cell(row=r, column=1, value=label).font = st["font"](bold=True)
    ws["B4"] = "=CONCATENATE('A - Table of Contents'!$C$3,\"/ \",'A - Table of Contents'!$C$4)"
    ws["B5"] = "=CONCATENATE('A - Table of Contents'!$C$5,\"/ \",'A - Table of Contents'!$C$6)"
    ws["B6"] = "=CONCATENATE('A - Table of Contents'!$C$7,\"/ \",'A - Table of Contents'!$C$8)"
    for coord in ("B4", "B5", "B6"):
        ws[coord].font = st["font"]()
    if exp.get("roles"):
        c = ws.cell(row=7, column=4, value=exp["roles"])
        c.font, c.fill, c.alignment = st["font"](bold=True), st["hdr_fill"], st["center"]
    c = ws.cell(row=7, column=N_AUTHORED + 1, value="Update during Test Execution")
    c.font, c.fill, c.alignment = st["font"](bold=True), st["exec_fill"], st["center"]
    for col, h in enumerate(TC_COLS, 1):
        c = ws.cell(row=TC_HEADER_ROW, column=col, value=h)
        c.font, c.alignment, c.border = st["font"](bold=True), st["center"], st["border"]
        c.fill = st["hdr_fill"] if col <= N_AUTHORED else st["exec_fill"]
    ws.row_dimensions[TC_HEADER_ROW].height = 38
    for col, w in COL_W.items():
        ws.column_dimensions[col].width = w
    ws.freeze_panes = f"A{TC_HEADER_ROW + 1}"

    all_tcs = [tc for _srel, _sfm, tcl in subs for tc in tcl]
    prd_secs, nums = [], []
    for _srel, sfm, tcl in subs:
        for sec in re.findall(r"§(\d[\d.]*)", (sfm or {}).get("description") or ""):
            if sec not in prd_secs:
                prd_secs.append(sec)
        for _rel, fm, _b in tcl:
            m = re.match(r"^(\d[\d.]*)-AC", fm["id"])
            if m and m.group(1) not in nums:
                nums.append(m.group(1))
    section = _plain((mod_fm or {}).get("title") or "Test Cases")
    if prd_secs:
        section += " - " + ", ".join(prd_secs)
    if nums:
        section += f" ({', '.join(nums)})"

    r = TC_HEADER_ROW + 1
    ws.cell(row=r, column=1, value=section).font = st["blue"]
    r += 1
    common = sheet_common(all_tcs)
    if common:
        ws.cell(row=r, column=1, value="<Pre-condition>").font = st["blue"]
        r += 1
        for i, ln in enumerate(common, 1):
            # blue block is whole-cell bold already — markers stripped, dashes fixed
            ws.cell(row=r, column=1, value=f"{i}. {_plain(ln)}").font = st["blue"]
            r += 1
    for _srel, sfm, tcl in subs:
        sub_title = _plain((sfm or {}).get("title") or "") or None
        if sub_title:
            for col in range(1, LAST_COL + 1):
                c = ws.cell(row=r, column=col)
                c.fill, c.border = st["sect_fill"], st["border"]
            ws.cell(row=r, column=1, value=sub_title).font = st["font"](bold=True)
            ws.row_dimensions[r].height = 21
            r += 1
        cur_section = None
        for _rel, fm, body in tcl:
            sec_name = fm.get("section")
            if sec_name and sec_name != cur_section:
                # logical separator: one row per flow section (tc-style R6)
                cur_section = sec_name
                for col in range(1, LAST_COL + 1):
                    c = ws.cell(row=r, column=col)
                    c.fill, c.border = st["flow_fill"], st["border"]
                ws.cell(row=r, column=1,
                        value=f"Section: {_plain(sec_name)}").font = st["font"](bold=True)
                ws.row_dimensions[r].height = 18
                r += 1
            cells = tc_cells(fm, body, concepts, common, qmap)
            vals = (cells["id"], cells["scenario"], cells["steps"],
                    cells["data"], cells["expected"])
            for col, v in enumerate(vals, 1):
                c = ws.cell(row=r, column=col, value=_richify(v))
                c.font, c.alignment, c.border = st["font"](), st["top"], st["border"]
            conf, remarks = cells["confidence"], cells["remarks"]
            c = ws.cell(row=r, column=6, value=conf)
            c.font, c.alignment, c.border = st["font"](bold=True), st["center"], st["border"]
            if conf in st["conf_fill"]:
                c.fill = st["conf_fill"][conf]
            c = ws.cell(row=r, column=7, value=_richify(remarks))
            c.font, c.alignment, c.border = st["font"](), st["top"], st["border"]
            for col in range(N_AUTHORED + 1, LAST_COL + 1):   # blank execution grid
                ws.cell(row=r, column=col).border = st["border"]
            ws.row_dimensions[r].height = _est_height(vals + (conf, remarks))
            r += 1


DOUBT_COLS = ("Question ID", "Question", "Status", "Test cases", "Lowest level",
              "Affected (TC id / column)", "Answer",
              "Observation", "Observed by", "Date")
DOUBT_COL_W = (16, 60, 16, 11, 13, 44, 20, 30, 14, 12)
N_DOUBT_AUTHORED = 7    # Question ID .. Answer; the rest is filled by testers


def _question_map(doubt_summaries):
    """{doubt id: question id} for every member of every question, from the
    summaries whose register is valid."""
    out = {}
    for s in doubt_summaries or []:
        if s.get("register_errors"):
            continue
        for q in s.get("questions") or []:
            for m in q.get("members") or []:
                out.setdefault(m["doubt"], q["id"])
    return out


def _doubt_sheet_rows(tcs, doubt_summaries):
    """Rows of the Doubts sheet for the selected test cases: one dict per
    question that touches a selected test case (impact order restricted to the
    selection), then one per ungrouped doubt of a selected test case."""
    by_sid = {fm.get("scenario_id"): fm for _r, fm, _b in tcs if fm.get("scenario_id")}
    tc_order = {sid: i for i, sid in enumerate(by_sid)}
    labels = dict(CONF_PARTS)
    part_order = {k: i for i, (k, _l) in enumerate(CONF_PARTS)}

    def affected(members):
        ms = sorted(members, key=lambda m: (tc_order[m["scenario_id"]],
                                            part_order.get(m["part"], 99), m["doubt"]))
        return [f"{_display_id(by_sid[m['scenario_id']])} / "
                f"{labels.get(m['part'], m['part'])}" for m in ms]

    questions, ungrouped = [], []
    for s in doubt_summaries or []:
        if s.get("register_errors"):
            pool = [d for d in s.get("doubts") or [] if d.get("state") != "closed"]
            ungrouped += [d for d in pool if d["scenario_id"] in by_sid]
            continue
        ungrouped += [d for d in s.get("ungrouped_doubts") or []
                      if d["scenario_id"] in by_sid]
        for q in s.get("questions") or []:
            mine = [m for m in q.get("members") or [] if m["scenario_id"] in by_sid]
            if not mine:
                continue
            live = [m for m in mine if m["state"] != "closed"]
            low = sum(1 for m in live if m["level"] == "Low")
            rids = sorted({m["resolution"] for m in mine if m.get("resolution")})
            questions.append({
                "id": q["id"], "question": q.get("question") or "",
                "status": q.get("status") or "",
                "tcs": len({m["scenario_id"] for m in mine}),
                "lowest": "Low" if low else "Medium" if live else "",
                "affected": affected(mine), "answer": ", ".join(rids),
                "_key": (-len({m["scenario_id"] for m in live}), -low, str(q["id"])),
            })
    questions.sort(key=lambda r: r["_key"])
    for r in questions:
        del r["_key"]
    rows = list(questions)
    for d in sorted(ungrouped, key=lambda d: d["doubt"]):
        rows.append({"id": "-", "question": d.get("remark") or "",
                     "status": "ungrouped", "tcs": 1,
                     "lowest": d["level"], "affected": affected([d]), "answer": ""})
    return rows


def _fill_doubts(ws, rows, st):
    for col, h in enumerate(DOUBT_COLS, 1):
        c = ws.cell(row=1, column=col, value=h)
        c.font, c.alignment, c.border = st["font"](bold=True), st["center"], st["border"]
        c.fill = st["hdr_fill"] if col <= N_DOUBT_AUTHORED else st["exec_fill"]
    ws.row_dimensions[1].height = 38
    for i, r in enumerate(rows, 2):
        vals = (r["id"], r["question"], r["status"], r["tcs"], r["lowest"],
                "\n".join(r["affected"]), r["answer"])
        for col, v in enumerate(vals, 1):
            c = ws.cell(row=i, column=col, value=_richify(v) if isinstance(v, str) else v)
            c.font, c.alignment, c.border = st["font"](), st["top"], st["border"]
        for col in range(N_DOUBT_AUTHORED + 1, len(DOUBT_COLS) + 1):
            ws.cell(row=i, column=col).border = st["border"]
        lines = max(sum(max(1, math.ceil(len(ln) / max(wd - 2, 10)))
                        for ln in _plain(v).split("\n"))
                    for v, wd in zip(vals, DOUBT_COL_W) if v)
        ws.row_dimensions[i].height = min(max(14 * lines, 20), 400)
    for i, w in enumerate(DOUBT_COL_W):
        ws.column_dimensions[chr(ord("A") + i)].width = w
    ws.freeze_panes = "A2"


def _fill_stats(ws, dashboards, st):
    """dashboards: [(title, tc_sheet_name, [display_id, ...]), ...]"""
    from openpyxl.utils import get_column_letter
    pct = "0.0%"
    end = STATS_FIRST_ID_ROW + max([len(d[2]) for d in dashboards] or [0]) - 1
    cols = [get_column_letter(2 + 3 * i) for i in range(len(dashboards))]
    scols = [get_column_letter(3 + 3 * i) for i in range(len(dashboards))]
    ws.cell(row=2, column=1, value="OVERALL").font = st["font"](bold=True, size=12)
    overall = (("Total TCs", 12), ("Pass", 14), ("Fail", 15), ("Block", 16),
               ("Void", 17), ("Not Yet Tested", 18), ("Pending Retest", 19))
    ws.cell(row=3, column=1, value="Total TCs").font = st["font"](bold=True)
    ws.cell(row=3, column=2, value="=" + "+".join(f"{c}12" for c in cols)).font = st["font"]()
    for i, (label, src_row) in enumerate(overall[1:], 4):
        ws.cell(row=i, column=1, value=label).font = st["font"]()
        ws.cell(row=i, column=2,
                value="=" + "+".join(f"{c}{src_row}" for c in cols)).font = st["font"]()
        c = ws.cell(row=i, column=3, value=f"=IFERROR(B{i}/$B$3,0)")
        c.font, c.number_format = st["font"](), pct
    for i, (title, _sheet, _ids) in enumerate(dashboards):
        c = ws.cell(row=11, column=2 + 3 * i, value=title)
        c.font, c.fill = st["font"](bold=True), st["hdr_fill"]
    per = (("Total TCs", 12, None),
           ("Total Executed (Pass + Fail)", 13, None)) + tuple(
        (s, 14 + j, s) for j, s in enumerate(STATUSES))
    for label, row, _s in per:
        ws.cell(row=row, column=1, value=label).font = st["font"]()
    for i, (title, _sheet, ids) in enumerate(dashboards):
        cl, sl = cols[i], scols[i]
        ws[f"{cl}12"] = f"=COUNTA({cl}${STATS_FIRST_ID_ROW}:{cl}${end})"
        ws[f"{cl}13"] = f"={cl}14+{cl}15"
        for j, status in enumerate(STATUSES):
            row = 14 + j
            ws[f"{cl}{row}"] = (f'=COUNTIF({sl}${STATS_FIRST_ID_ROW}:{sl}${end},'
                                f'"{status}")')
            c = ws[f"{sl}{row}"]
            c.value, c.number_format = f"=IFERROR({cl}{row}/{cl}$12,0)", pct
        for coord, h in ((f"{cl}21", "Test Case ID"), (f"{sl}21", "Status")):
            ws[coord] = h
            ws[coord].font, ws[coord].fill = st["font"](bold=True), st["hdr_fill"]
            ws[coord].border = st["border"]
        sheet_ref = dashboards[i][1]
        for j, tid in enumerate(ids):
            row = STATS_FIRST_ID_ROW + j
            a = ws[f"{cl}{row}"]
            a.value, a.font, a.border = tid, st["font"](), st["border"]
            b = ws[f"{sl}{row}"]
            b.value = (f"=VLOOKUP({cl}{row},'{sheet_ref}'!$A:$N,"
                       f"{STATUS_COL},FALSE)")
            b.font, b.border = st["font"](), st["border"]
    ws.column_dimensions["A"].width = 28
    for c in cols:
        ws.column_dimensions[c].width = 26
    for c in scols:
        ws.column_dimensions[c].width = 16


def change_rows(changes, dash_of, draft=False):
    """Rows (Dashboard, Test Case ID, Description of Change) for the Change
    Log sheet. `dash_of` maps display id -> sub-story title."""
    if draft:
        return [("", "", "Draft round 0 - no changes yet.")]
    if not changes:
        return [("", "", "No current change log - run eval_rubric --diff on "
                 "this sealed set.")]
    to = changes.get("to") or {}
    rounds = {r["round"]: r["score"] for r in changes.get("rounds") or []}
    delta = changes.get("delta")
    sign = f"{delta:+}" if isinstance(delta, (int, float)) else ""
    if changes.get("regression_restored"):
        head = (f"Graded round {to.get('round')}: {to.get('score')} (round 2 "
                f"regressed to {rounds.get(2)}, {sign}; round 1 kept), "
                f"rubric {changes.get('rubric_version', '')}")
    elif to.get("round") and to["round"] - 1 in rounds:
        head = (f"Graded round {to['round']}: {to.get('score')} (round "
                f"{to['round'] - 1}: {rounds[to['round'] - 1]}, {sign}), "
                f"rubric {changes.get('rubric_version', '')}")
    else:
        head = (f"Graded round {to.get('round')}: {to.get('score')}, "
                f"rubric {changes.get('rubric_version', '')}")
    rows = [("", "", head)]
    grouped = {}          # tc -> (kind, fields, closes, extra) in first-seen order
    for c in changes.get("changes") or []:
        tid = c["tc"]
        kind = c["kind"]
        if kind not in ("added", "removed", "changed"):
            raise ValueError(f"change_rows: unknown change kind {kind!r} for {tid}")
        disp = _display_id({"id": tid})
        g = grouped.setdefault(disp, {"kind": kind, "fields": [], "closes": [],
                                      "title": c.get("title", ""), "reason": c.get("reason", "")})
        if c.get("field") and c["field"] not in g["fields"]:
            g["fields"].append(c["field"])
        for cl in (c.get("closes") or "").split(","):
            cl = cl.strip()
            if cl and cl not in g["closes"]:
                g["closes"].append(cl)
    for disp, g in grouped.items():
        closes = f" (closes {', '.join(g['closes'])})" if g["closes"] else ""
        if g["kind"] == "added":
            desc = f"Added - {g['title']}{closes}"
        elif g["kind"] == "removed":
            desc = f"Removed - {g['reason'] or 'not in the current set'}"
        elif g["kind"] == "changed":
            desc = f"Changed {', '.join(g['fields'])}{closes}"
        rows.append((dash_of.get(disp, ""), disp, desc))
    return rows


def _fill_change_log(ws, st, rows):
    for col, h in enumerate(("Dashboard", "Test Case ID", "Description of Change"), 1):
        c = ws.cell(row=1, column=col, value=h)
        c.font, c.fill, c.border = st["font"](bold=True), st["hdr_fill"], st["border"]
    for col, w in (("A", 30), ("B", 26), ("C", 70)):
        ws.column_dimensions[col].width = w
    for r, (dash, tid, desc) in enumerate(rows, 2):
        for col, v in enumerate((dash, tid, desc), 1):
            c = ws.cell(row=r, column=col, value=v)
            c.font, c.border, c.alignment = st["font"](), st["border"], st["top"]


def render_xlsx(tcs, title, xlsx_path, concepts=None, manifest=None,
                test_type="SIT", doubt_summaries=None, draft=False,
                grade=None, changes=None, change_log=True):
    """Render the SIT workbook (template: tools/reference-format-sit.xlsx).
    `change_log=False` (suite compiles: a selection, not a scope delivery)
    leaves the Change Log sheet with its header row only."""
    from openpyxl import Workbook
    concepts = concepts or {}
    manifest = manifest or {}
    cfg = load_config()
    exp = cfg.get("export") or {}
    st = _styles()
    groups = _group(tcs, concepts)

    sheets = plan_sheets(tcs, concepts)
    names = [n for n, _m, _s, _t in sheets]
    if len({n.lower() for n in names}) != len(names):
        sys.exit(f"export refused: two worksheets would share a name {names} - "
                 f"rename a run or a module so their sheet names differ")
    tc_sheet_names = names
    qmap = _question_map(doubt_summaries)
    doubt_rows = _doubt_sheet_rows(tcs, doubt_summaries) if doubt_summaries else []
    prefix = exp.get("module_prefix")
    module_name = _plain(" / ".join(
        f"{prefix} - {(mfm or {}).get('title', '?')}" if prefix
        else (mfm or {}).get("title", "?") for _r, mfm, _s in groups) or title)
    meta = dict(
        module_name=module_name,
        test_type=test_type,
        version=f"v{cfg.get('project', {}).get('okf_version', '0.1')}",
        date=date.today().strftime("%d %b %Y"),
        prepared_date=datetime.now().strftime("%d %b %Y, %H:%M"),
        tabs=[("A - Table of Contents", "Table of Contents"),
              ("B - Proj Doc References", "Project Document References")]
             + [(n, "Test Case") for n in tc_sheet_names]
             + ([("Doubts", "Doubts")] if doubt_rows else [])
             + [("Test Statistics", "Test Statistics"),
                ("Change Log", "Change Log")],
        docs=prd_docs(tcs, manifest, cfg.get("project", {}).get("name", "")),
    )
    if draft:
        meta.update(version="DRAFT r0", title_prefix="DRAFT (ungraded, round 0) - ",
                    revision_summary=("DRAFT first cut - rendered and sealed, not yet "
                                      "graded against the ISO/IEC/IEEE 29119-4 rubric. "
                                      "A final workbook with a Change Log follows."))
    elif grade:
        meta.update(version=f"r{grade['round']} · rubric {grade['score']}",
                    revision_summary=(f"Graded round {grade['round']}: score "
                                      f"{grade['score']} (threshold {grade['threshold']}), "
                                      f"rubric {grade['version']}"))

    wb = Workbook()
    # pinned doc properties: identical inputs -> byte-identical workbook
    # the author is left blank: the workbook names no tool or person unless
    # config export.prepared_by gives one for the visible Prepared by cells
    wb.properties.creator = ""
    wb.properties.created = wb.properties.modified = datetime(2026, 1, 1)
    _fill_toc(wb.active, exp, meta, st)
    wb.active.title = "A - Table of Contents"
    _fill_refs(wb.create_sheet("B - Proj Doc References"), meta, st)
    dashboards = []
    for name, mod_fm, subs, dash_title in sheets:
        ws = wb.create_sheet(name)
        _fill_tc_sheet(ws, mod_fm, subs, concepts, exp, st, qmap)
        if dash_title:       # a run sheet: one dashboard block for the sheet
            dashboards.append((_plain(dash_title), name,
                               [_display_id(fm) for _s, _f, tcl in subs
                                for _r, fm, _b in tcl]))
            continue
        for _srel, sfm, tcl in subs:
            dashboards.append((_plain((sfm or {}).get("title") or title),
                               name,
                               [_display_id(fm) for _r, fm, _b in tcl]))
    if doubt_rows:
        _fill_doubts(wb.create_sheet("Doubts"), doubt_rows, st)
    _fill_stats(wb.create_sheet("Test Statistics"), dashboards, st)
    dash_of = {}
    for _mrel, _mod_fm, subs in groups:
        for _srel, sfm, tcl in subs:
            for _r, fm, _b in tcl:
                dash_of[_display_id(fm)] = _plain((sfm or {}).get("title") or title)
    _fill_change_log(wb.create_sheet("Change Log"), st,
                     change_rows(changes, dash_of, draft=draft) if change_log else [])
    wb.save(xlsx_path)
    # The refs in the order the workbook holds them (sheet, then row), from the
    # same plan the sheets were drawn from: the sidecar records this order.
    return [rel for _n, _m, subs, _t in sheets
            for _srel, _sfm, tcl in subs for rel, _fm, _b in tcl]


def inventory_paths(name, kind):
    """Timestamped xlsx/md paths under build/inventory/<kind>/, plus the
    stable '-latest' copies scripts/smoke/COM snippets read from.
    Returns (outdir, xlsx_ts, md_ts, xlsx_latest, md_latest)."""
    outdir = ROOT / "build/inventory" / kind
    outdir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    xlsx_ts = outdir / f"{name}_{ts}.xlsx"
    md_ts = outdir / f"{name}_{ts}.md"
    xlsx_latest = outdir / f"{name}-latest.xlsx"
    md_latest = outdir / f"{name}-latest.md"
    return outdir, xlsx_ts, md_ts, xlsx_latest, md_latest


def write_sidecar(xlsx_path, source, tc_rels, manifest):
    """Record what a compiled workbook was built from, beside it: the compile
    time, the wiki commit, the source (suite or export) and the sealed hash of
    every test case in it. The operator app compares these hashes with the
    manifest to say which rows changed since the compile. Returns the path
    written (`xlsx_path` with a .json suffix). build/ is a compiled view: this
    is called only by `suite compile` and `export`, and the file is never
    edited. `tc_rels` must be in the order the workbook holds the rows (what
    `render_xlsx` returns); `tcs_order: "sheet"` records that promise."""
    import json
    import subprocess
    hashes = manifest.get("tc_hashes") or {}
    head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                          capture_output=True, text=True)
    doc = {"compiled_at": now_iso(),
           "wiki_commit": head.stdout.strip() if head.returncode == 0 else None,
           "source": source,
           "tcs_order": "sheet",
           "tcs": {rel: hashes.get(rel) for rel in tc_rels}}
    path = Path(xlsx_path).with_suffix(".json")
    path.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n",
                    encoding="utf-8", newline="\n")
    return path


def doubt_summaries(root=None):
    """The story summaries for the Doubts sheet, or None (no sheet) when
    they cannot be computed: open doubts never block an export."""
    import wiki_doubts
    try:
        return [wiki_doubts.story_summary(s, root=root)
                for s in wiki_doubts.stories_with_doubts(root)]
    except Exception as e:  # a bad register or spec must not stop the export
        print(f"warning: the Doubts sheet is left out ({type(e).__name__}: "
              f"{e}) - run: py tools/wiki.py lint", file=sys.stderr)
        return None


def compile_suite(name, graph=False):
    import shutil
    spath = ROOT / "suites" / f"{name}.yaml"
    if not spath.exists():
        sys.exit(f"suite compile: suites/{name}.yaml not found")
    from wiki import refuse_if_unsealed
    refuse_if_unsealed(f"suite compile {name}")
    suite = yaml.safe_load(spath.read_text(encoding="utf-8"))
    concepts, manifest = load_all()
    try:
        check_prd_filters(suite, manifest)
    except ValueError as e:
        sys.exit(f"suite compile {name} refused: {e}")
    selected, retired, stale = select(suite, concepts)

    title = f"Suite: {name}"
    kind = suite.get("kind", "sit")
    outdir, xlsx_ts, md_ts, xlsx_latest, md_latest = inventory_paths(name, kind)
    summaries = doubt_summaries()
    sheet_order = render_xlsx(selected, title, xlsx_ts, concepts=concepts,
                              manifest=manifest, doubt_summaries=summaries,
                              test_type={"mixed": "SIT+UAT"}.get(kind, kind.upper()),
                              change_log=False)
    # The sidecar is written before -latest is touched: if it cannot be
    # written, the old -latest pair stays a pair. The workbook is copied
    # before its sidecar, so a copy that fails (the file is open in Excel)
    # also leaves the old pair, never a new sidecar vouching for an old file.
    sidecar = write_sidecar(xlsx_ts, {"type": "suite", "name": name},
                            sheet_order, manifest)
    shutil.copyfile(xlsx_ts, xlsx_latest)
    shutil.copyfile(sidecar, xlsx_latest.with_suffix(".json"))

    md = [HEADER, f"# Inventory: {name}", "",
          f"- kind: {suite.get('kind')} · PRDs: "
          f"{', '.join(prd_names(selected, manifest)) or 'none'} "
          f"· active TCs: {len(selected)}",
          f"- filters: include_modules={suite.get('include_modules') or 'all'}, "
          f"exclude_modules={suite.get('exclude_modules') or []}, "
          f"include_prds={suite.get('include_prds') or 'all'}, "
          f"exclude_prds={suite.get('exclude_prds') or []}, "
          f"priorities={suite.get('priorities') or 'all'}", ""]
    for _rel, fm, _b in selected:
        md.append(f"- **{fm['id']}** [{fm.get('priority')}/{fm.get('technique')}] - "
                  f"{fm['title']}")
    if stale:
        md += ["", "## Stale (excluded - pending human decision)", ""]
        md += [f"- {fm['id']} - stale_because: "
               f"{[c['cause'] for c in fm.get('stale_because') or []]}"
               for _r, fm, _b in stale]
    md += ["", "## Retired (never deleted - spec §13.4)", ""]
    md += ([f"- {fm['id']} - {(fm.get('retirement') or {}).get('reason', '?')}"
            for _r, fm, _b in retired] or ["_None._"])
    md.append("")
    md_text = "\n".join(md)
    md_ts.write_text(md_text, encoding="utf-8", newline="\n")
    shutil.copyfile(md_ts, md_latest)
    rel_ts = xlsx_ts.relative_to(ROOT).as_posix()
    print(f"suite {name}: {len(selected)} active, {len(stale)} stale (excluded), "
          f"{len(retired)} retired -> {rel_ts} (+ {xlsx_latest.name})")

    from wiki_graph import build_model, emit, scope_suite
    model = build_model(concepts, manifest)
    tc_rels = [rel for rel, _fm, _body in selected]
    emit(f"suite-{name}", scope_suite(model, tc_rels, name), make_html=graph)


def cmd_suite(args):
    if not args:
        sys.exit("usage: wiki suite compile <name>")
    if args[0] == "compile":
        compile_suite(args[1], graph="--graph" in args)
    else:
        sys.exit(f"unknown suite subcommand {args[0]} (NL authoring is the "
                 "tc-suite-author skill; the YAML is the artifact of record)")
