#!/usr/bin/env python3
"""Coverage diagram (skill-revamp spec D2): Component x AC matrix + gaps.

Deterministic and product-agnostic: matches component NAMES from the story's
own component table against its own AC texts. `--propose` writes the
heuristic map to the story at coverage_status: proposed — confirmation is a
human-gated act performed by the tc-generate-sit skill's coverage card.
"""
import sys

from wiki import (ROOT, agent_commit, append_log, arg_after, load_all,
                  read_concept, resolve_ref, write_concept)

HEADER = ("<!-- generated by wiki coverage — reproducible from wiki + "
          "manifest; do not edit -->\n")


def name_variants(cmp):
    """Deterministic aliases derived from the component's own name."""
    name = (cmp.get("name") or "").strip()
    out = {name}
    if ":" in name:                       # "Bar Chart: Vehicle Status"
        out.add(name.split(":", 1)[1].strip())
    if "<" in name:                       # "Data last retrieved on <...>"
        out.add(name.split("<", 1)[0].strip())
    return {v for v in out if len(v) >= 3}


def propose_map(fm):
    """[{ac, components}] — longest-name-first with masking so a long match
    (e.g. 'Foo Bar Table') hides its substrings ('Foo Bar') from shorter
    component names."""
    cand = []
    for c in fm.get("components") or []:
        for v in name_variants(c):
            cand.append((v, c["id"]))
    cand.sort(key=lambda t: (-len(t[0]), t[1]))
    out = []
    for ac in fm.get("acceptance_criteria") or []:
        masked = " ".join((ac.get("text") or "").split()).lower()
        hits = []
        for v, cid in cand:
            i = masked.find(v.lower())
            while i >= 0:
                ok_l = i == 0 or not masked[i - 1].isalnum()
                j = i + len(v)
                ok_r = j >= len(masked) or not masked[j].isalnum()
                if ok_l and ok_r:
                    if cid not in hits:
                        hits.append(cid)
                    masked = masked[:i] + "\x00" * len(v) + masked[j:]
                    break
                i = masked.find(v.lower(), i + 1)
        out.append({"ac": ac["id"], "components": hits})
    return out


def components_covering(cmap, comp_id):
    """AC ids in `cmap` whose component list includes `comp_id`."""
    return [a for a, cl in cmap.items() if comp_id in cl]


def ac_active_counts(story_rel, acs, concepts, manifest):
    """{ac_id: count of ACTIVE covering TCs}. Single source for both the
    coverage MD render and the coverage graph, so their 'active' rule cannot drift."""
    ac_active = {a: 0 for a in acs}
    for s, k, t in manifest.get("edges", []):
        if k == "covers" and t.startswith(story_rel + "#"):
            frag = t.split("#", 1)[1]
            cfm = concepts.get(s, (None,))[0]
            if frag in ac_active and cfm and cfm.get("status") == "active":
                ac_active[frag] += 1
    return ac_active


def load_coverage(fm):
    cmap = {e["ac"]: list(e.get("components") or [])
            for e in fm.get("coverage_map") or []}
    disp = {d["component"]: d.get("note", "")
            for d in fm.get("component_dispositions") or []
            if d.get("disposition") == "out-of-scope"}
    return cmap, disp, fm.get("coverage_status")


def unconfirmed_members(journey, concepts):
    """Display labels for every story a journey touches whose coverage_status is
    not 'confirmed'. The coverage_map IS UAT test content — each TC enumerates
    the mapped components verbatim — so an uncorrected map would bake the
    heuristic's mistakes into tester-facing test cases (tc-generate-uat hard
    rule). De-duplicated, first-encounter order."""
    from wiki import resolve_ref
    out = []
    for entry in journey or []:
        srel, _frag = resolve_ref(entry["ref"])
        rec = concepts.get(srel)
        if not rec:
            continue
        sfm = rec[0] or {}
        status = load_coverage(sfm)[2]
        if status == "confirmed":
            continue
        label = f"{sfm.get('id', srel)} ({status or 'absent'})"
        if label not in out:
            out.append(label)
    return out


def coverage_states(story_rel, fm, concepts, manifest):
    """Node ref -> confidence state for the story's ACs and components,
    reusing the same booleans render() computes. Deterministic."""
    cmap, disp, _status = load_coverage(fm)
    acs = [a["id"] for a in fm.get("acceptance_criteria") or []]
    voided = {a["id"] for a in fm.get("acceptance_criteria") or []
              if a.get("status") == "voided"}
    ac_active = ac_active_counts(story_rel, acs, concepts, manifest)
    state = {}
    for a in acs:
        state[f"{story_rel}#{a}"] = ("voided" if a in voided
                                     else "covered" if ac_active[a] else "GAP")
    for c in fm.get("components") or []:
        covering = components_covering(cmap, c["id"])
        tc_n = sum(ac_active.get(a, 0) for a in covering)
        if covering:
            st = "covered" if tc_n else "ACs-without-TCs"
        elif c["id"] in disp:
            st = "out-of-scope"
        else:
            st = "GAP"
        state[f"{story_rel}#{c['id']}"] = st
    return state


# ── Element verification block (org convention) ───────────────────────────────
# Deterministic, product-agnostic renderer: an org-style lettered list of the
# UI elements a story's confirmed coverage_map ties to one AC. Everything is read
# from the component entry — nothing product-specific is hardcoded here.

KIND_PREFIX = {"label": "Label", "button": "Button", "dropdown": "Label / Dropdown",
               "chart": "Bar Chart", "table": "Table", "chip-group": "Buttons / Filter Chips",
               "hyperlink": "Hyperlink", "chip": "Button / Filter Chip"}

# Single-value sub-bullets rendered in this fixed order (key -> displayed label).
_SUB_SINGLE = (("x_axis", "X-Axis"), ("y_axis", "Y-Axis"), ("groups", "Groups"))
# Comma-list sub-bullets: one bullet per comma-separated entry.
_SUB_LISTS = (("columns", "List of Label(s)"),
              ("nested_columns", "Nested table Label(s)"))


def _letter(i):
    """0->a, 25->z, 26->aa, ... (bijective base-26)."""
    s = ""
    i += 1
    while i > 0:
        i, r = divmod(i - 1, 26)
        s = chr(97 + r) + s
    return s


def element_verification_block_multi(story_fm, ac_ids, indent="    "):
    """Org-style lettered element list for the UNION of the components mapped to
    every AC in ac_ids (coverage_map order within each AC, ac_ids order across
    them), deduped by component id (first occurrence wins) with letters running
    continuous across the union. Deterministic from the component table; returns
    "" when nothing is mapped."""
    cmap, _disp, _status = load_coverage(story_fm)
    by_id = {c["id"]: c for c in story_fm.get("components") or []}
    ordered = []
    seen = set()
    for ac_id in ac_ids:
        for cid in cmap.get(ac_id) or []:
            if cid not in seen:
                seen.add(cid)
                ordered.append(cid)
    sub = indent + indent
    lines = []
    n = 0
    for cid in ordered:
        c = by_id.get(cid)
        if not c:
            continue
        kind = c.get("kind", "element")
        prefix = KIND_PREFIX.get(kind, kind.title())
        props = c.get("properties") or {}
        # Main line: the component name, unless it is a chip group — chips render
        # inline on the main line joined with " | ".
        if "chips" in props:
            main = " | ".join(x.strip() for x in str(props["chips"]).split(",")
                              if x.strip())
        else:
            main = c.get("name", cid)
        # tc-style R4: element names render bold (export converts the markers)
        lines.append(f"{indent}{_letter(n)}. {prefix} : **{main}**")
        n += 1
        for key, label in _SUB_SINGLE:
            if props.get(key):
                lines.append(f"{sub}• **{label}** : {props[key]}")
        for key, label in _SUB_LISTS:
            if props.get(key):
                for col in str(props[key]).split(","):
                    if col.strip():
                        lines.append(f"{sub}• **{label}** : {col.strip()}")
        if props.get("target"):
            lines.append(f"{sub}• **Navigates to** : {props['target']}")
    return "\n".join(lines)


def element_verification_block(story_fm, ac_id, indent="    "):
    """Org-style lettered element list for the components mapped to ac_id.
    Thin wrapper over element_verification_block_multi for a single AC."""
    return element_verification_block_multi(story_fm, [ac_id], indent)


def render(story_id, fm, concepts, manifest):
    cmap, disp, status = load_coverage(fm)
    story_rel = f"stories/{story_id}"
    comps = fm.get("components") or []
    acs = [a["id"] for a in fm.get("acceptance_criteria") or []]
    ac_active = ac_active_counts(story_rel, acs, concepts, manifest)
    lines = [HEADER, f"# Coverage: {story_id} "
             f"(coverage_status: {status or 'ABSENT'})", "",
             "| Component | Covering ACs | Active TCs via those ACs | State |",
             "|---|---|---|---|"]
    gaps = []
    for c in comps:
        covering = components_covering(cmap, c["id"])
        tc_n = sum(ac_active.get(a, 0) for a in covering)
        if covering:
            state = "covered" if tc_n else "ACs-without-TCs"
        elif c["id"] in disp:
            state = f"out-of-scope: {disp[c['id']]}"
        else:
            state = "GAP - no AC"
            gaps.append(c)
        lines.append(f"| {c['id']} {c.get('name', '')} | "
                     f"{', '.join(covering) or '—'} | {tc_n} | {state} |")
    unmapped = [a for a in acs if not cmap.get(a)] if cmap else []
    lines += ["", "## Components with NO covering AC (undispositioned gaps)", ""]
    lines += [f"- {c['id']} — {c.get('name', '')}" for c in gaps] or ["_None._"]
    lines += ["", "## ACs with no mapped component", ""]
    lines += ([f"- {a}" for a in unmapped] or ["_None._"]) if cmap else \
        ["_(no coverage_map on story — run with --propose)_"]
    lines.append("")
    outdir = ROOT / "build/rtm"
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / f"coverage-{story_id}.md").write_text(
        "\n".join(lines), encoding="utf-8", newline="\n")
    return len(gaps), len(unmapped)


def cmd_coverage(args):
    story_id = arg_after(args, "--story")
    p = ROOT / "stories" / f"{story_id}.md"
    if not p.exists():
        sys.exit(f"coverage: story {story_id} not found")
    fm, body = read_concept(p)
    if "--propose" in args:
        if fm.get("coverage_status") == "confirmed":
            sys.exit("coverage: map is confirmed — correcting a confirmed map "
                     "is human-gated (card flow); refusing regardless of --force")
        if fm.get("coverage_map") and "--force" not in args:
            sys.exit(f"coverage: {story_id} already has a coverage_map "
                     "(use --force to overwrite the PROPOSED map)")
        fm["coverage_map"] = propose_map(fm)
        fm["coverage_status"] = "proposed"
        write_concept(p, fm, body)
        append_log(f"**Coverage (agent)**: heuristic map proposed for {story_id}")
        print(f"proposed coverage_map written to {story_id} "
              f"({len(fm['coverage_map'])} AC entries)")
    concepts, manifest = load_all()
    fm, _ = read_concept(p)
    ngaps, nunmapped = render(story_id, fm, concepts, manifest)
    print(f"coverage {story_id}: {ngaps} component gap(s), "
          f"{nunmapped} unmapped AC(s) -> build/rtm/coverage-{story_id}.md")
    agent_commit(f"coverage({story_id}): "
                 f"{'propose + ' if '--propose' in args else ''}render")
    from wiki_graph import build_model, emit, scope_coverage
    model = build_model(concepts, manifest)
    srel = f"stories/{story_id}"
    states = coverage_states(srel, concepts[srel][0], concepts, manifest)
    emit(f"coverage-{story_id}",
         scope_coverage(model, srel, state_by_ref=states),
         make_html="--graph" in args)
